#!/usr/bin/env python3
"""Capture PuLID v1.1 (SDXL) `IDFormer` goldens from upstream PyTorch.

PROVENANCE ONLY. Nothing in mold's build or test path executes this file, and
mold ships no Python.

Runs upstream `ToTheBeginning/PuLID`'s own `pulid/encoders_transformer.py
::IDFormer` — the SAME class the FLUX adapter uses (see
`crates/mold-inference/testdata/pulid/capture_eva_goldens.py`), loaded
strictly from `pulid_v1.1.safetensors`'s `id_adapter.*` tensors (v1.1 uses that
prefix; the FLUX checkpoint uses `pulid_encoder.*` — see
`pulid/pipeline_v1_1.py:151-163`'s `load_pretrain`, which splits the
checkpoint by leading module name) — on synthetic inputs generated by the same
`xorshift64*` stream `capture_eva_goldens.py::DeterministicStream` and
`crates/mold-inference/src/pulid_fixtures.rs::DeterministicStream` already
share.

IMPORTANT — the id_cond dimension is 1280, not 1792. `id_cond =
torch.cat([id_ante_embedding, id_cond_vit], dim=-1)` (`pipeline_v1_1.py:230`)
concatenates the antelopev2 ArcFace embedding (512) with the EVA02-CLIP-L-14-336
projected CLS token (768, `eva_clip/model_configs/EVA02-CLIP-L-14-336.json`'s
`embed_dim`) — 512 + 768 = 1280, confirmed by the checkpoint's own
`id_adapter.id_embedding_mapping.0.weight` shape `[1024, 1280]` (`nn.Linear`
stores `[out_features, in_features]`). This is IDENTICAL to the FLUX
adapter's `ID_COND_DIM` in `capture_true_cfg_goldens.py`. Do not "correct"
this back to 1792 without re-deriving it from the checkpoint header.

Three cases are captured, per `pipeline_v1_1.py::get_id_embedding`
(lines 208-259):
  - single image: id_cond [1, 1, 1280], five hidden states [1, 577, 1024]
    (`x.ndim == 3` so `num_duotu = x.shape[1] == 1`, line 224-227)
  - uncond: id_cond and every hidden state zeroed (lines 243-247) — the
    embedding PuLID's negative branch conditions on
    (`cross_attention_kwargs={'id_embedding': uncond_id_embedding, ...}`,
    `pipeline_v1_1.py:314`)
  - two images: id_cond [1, 2, 1280] (`torch.stack(id_cond_list, dim=1)`,
    line 249), hidden states concatenated along dim=1 to [1, 1154, 1024]
    per scale (`id_vit_hidden[j] = torch.cat([id_vit_hidden[j], x], dim=1)`,
    lines 253-256)

Usage (scratch venv; torch CPU + safetensors):

    python capture_idformer_goldens.py \
        --pulid-repo /path/to/PuLID \
        --adapter /path/to/pulid_v1.1.safetensors \
        --out .
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

import numpy as np
import torch
from safetensors.torch import load_file, save_file

MULT = 0x2545F4914F6CDD1D
MASK = (1 << 64) - 1


class DeterministicStream:
    """`xorshift64*` — bit-identical to `capture_eva_goldens.py`'s copy and to
    `crates/mold-inference/src/pulid_fixtures.rs::DeterministicStream`."""

    def __init__(self, seed: int) -> None:
        assert seed != 0
        self.state = seed & MASK

    def next_u64(self) -> int:
        x = self.state
        x ^= x >> 12
        x &= MASK
        x ^= (x << 25) & MASK
        x ^= x >> 27
        self.state = x & MASK
        return (x * MULT) & MASK

    def next_unit(self) -> float:
        return np.float32(((self.next_u64() >> 11) / float(1 << 53)) * 2.0 - 1.0)

    def tensor(self, *shape: int) -> torch.Tensor:
        n = 1
        for d in shape:
            n *= d
        flat = np.fromiter((self.next_unit() for _ in range(n)), np.float32, n)
        return torch.from_numpy(flat.reshape(shape))


# New seeds, distinct from the FLUX set in capture_eva_goldens.py (different
# testdata directory, but seeds are cheap and collision-free is simpler to
# audit than shared). ASCII spells "PULIDSX*".
SEED_ID_COND = 0x50554C4944535849  # "PULIDSXI"
SEED_VIT_HIDDEN = 0x50554C4944535856  # "PULIDSXV"
SEED_ID_COND_2ND = 0x50554C4944535832  # "PULIDSX2" — second image's id_cond

ID_COND_DIM = 512 + 768  # arcface + eva-clip-l-14-336 projected CLS
VIT_SCALES = 5
VIT_TOKENS = 577
VIT_DIM = 1024


def stats(t: torch.Tensor) -> dict:
    f = t.double().flatten()
    return {
        "shape": list(t.shape),
        "mean": float(f.mean()),
        "std": float(f.std(unbiased=False)),
        "min": float(f.min()),
        "max": float(f.max()),
        "l2": float(f.norm(2)),
    }


STAT_SLOTS = ("mean", "std", "min", "max", "peak")


def stats_tensor(t: torch.Tensor) -> torch.Tensor:
    f = t.double().flatten()
    return torch.tensor(
        [
            float(f.mean()),
            float(f.std(unbiased=False)),
            float(f.min()),
            float(f.max()),
            float(f.abs().max()),
        ],
        dtype=torch.float32,
    )


def load_idformer(pulid_repo: Path, adapter: Path):
    sys.path.insert(0, str(pulid_repo))
    from pulid.encoders_transformer import IDFormer

    model = IDFormer().eval().float()
    state = load_file(str(adapter))
    prefix = "id_adapter."
    encoder_state = {
        k[len(prefix):]: v.float() for k, v in state.items() if k.startswith(prefix)
    }
    missing = model.load_state_dict(encoder_state, strict=True)
    assert not missing.missing_keys and not missing.unexpected_keys, missing
    return model


def cast_round_trip_f16(t: torch.Tensor) -> torch.Tensor:
    return t.half().float()


def run_case(model, id_cond: torch.Tensor, vit_hidden: list[torch.Tensor]) -> torch.Tensor:
    with torch.no_grad():
        out = model(id_cond, vit_hidden)
    return out


def capture(pulid_repo: Path, adapter: Path, cast_f16_inputs: bool) -> tuple[dict, dict]:
    model = load_idformer(pulid_repo, adapter)

    def maybe_cast(t: torch.Tensor) -> torch.Tensor:
        return cast_round_trip_f16(t) if cast_f16_inputs else t

    # --- single image ---
    id_cond_single = maybe_cast(DeterministicStream(SEED_ID_COND).tensor(1, 1, ID_COND_DIM))
    vit_hidden_single = [
        maybe_cast(DeterministicStream(SEED_VIT_HIDDEN + i).tensor(1, VIT_TOKENS, VIT_DIM))
        for i in range(VIT_SCALES)
    ]
    out_single = run_case(model, id_cond_single, vit_hidden_single)
    assert tuple(out_single.shape) == (1, 32, 2048), out_single.shape

    # --- uncond: everything zeroed, per pipeline_v1_1.py:243-247 ---
    id_cond_uncond = torch.zeros_like(id_cond_single)
    vit_hidden_uncond = [torch.zeros_like(h) for h in vit_hidden_single]
    out_uncond = run_case(model, id_cond_uncond, vit_hidden_uncond)
    assert tuple(out_uncond.shape) == (1, 32, 2048), out_uncond.shape

    # --- two images: stack id_cond along dim=1, concat hidden states along
    # dim=1 per scale (pipeline_v1_1.py:249-256) ---
    id_cond_2nd = maybe_cast(DeterministicStream(SEED_ID_COND_2ND).tensor(1, 1, ID_COND_DIM))
    id_cond_two = torch.cat([id_cond_single, id_cond_2nd], dim=1)
    assert tuple(id_cond_two.shape) == (1, 2, ID_COND_DIM), id_cond_two.shape

    vit_hidden_2nd = [
        maybe_cast(DeterministicStream(SEED_VIT_HIDDEN + i + 100).tensor(1, VIT_TOKENS, VIT_DIM))
        for i in range(VIT_SCALES)
    ]
    vit_hidden_two = [
        torch.cat([vit_hidden_single[i], vit_hidden_2nd[i]], dim=1) for i in range(VIT_SCALES)
    ]
    for h in vit_hidden_two:
        assert tuple(h.shape) == (1, 2 * VIT_TOKENS, VIT_DIM), h.shape

    out_two = run_case(model, id_cond_two, vit_hidden_two)
    assert tuple(out_two.shape) == (1, 32, 2048), out_two.shape

    arrays = {
        "idformer.single.output": out_single[0].contiguous(),
        "idformer.single.output.stats": stats_tensor(out_single),
        "idformer.uncond.output": out_uncond[0].contiguous(),
        "idformer.uncond.output.stats": stats_tensor(out_uncond),
        "idformer.two_image.output": out_two[0].contiguous(),
        "idformer.two_image.output.stats": stats_tensor(out_two),
    }
    meta = {
        "note": (
            "id_cond dim is 1280 (512 arcface + 768 eva-clip-l-14-336 proj), "
            "NOT 1792 — verified against id_adapter.id_embedding_mapping.0.weight "
            "== [1024, 1280] in the checkpoint header"
        ),
        "id_cond_dim": ID_COND_DIM,
        "vit_scales": VIT_SCALES,
        "vit_tokens": VIT_TOKENS,
        "vit_dim": VIT_DIM,
        "stat_slots": list(STAT_SLOTS),
        "seeds": {
            "id_cond": hex(SEED_ID_COND),
            "vit_hidden_base": hex(SEED_VIT_HIDDEN),
            "id_cond_2nd_image": hex(SEED_ID_COND_2ND),
        },
        "cast_f16_inputs": cast_f16_inputs,
        "single": {
            "id_cond_shape": [1, 1, ID_COND_DIM],
            "vit_hidden_shape": [VIT_SCALES, 1, VIT_TOKENS, VIT_DIM],
            "output": stats(out_single),
        },
        "uncond": {
            "source": "pipeline_v1_1.py:243-247 — zeros of the single-image shapes above",
            "output": stats(out_uncond),
        },
        "two_image": {
            "id_cond_shape": [1, 2, ID_COND_DIM],
            "vit_hidden_shape": [VIT_SCALES, 1, 2 * VIT_TOKENS, VIT_DIM],
            "output": stats(out_two),
        },
    }
    return arrays, meta


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--pulid-repo", type=Path, required=True)
    parser.add_argument("--adapter", type=Path, required=True)
    parser.add_argument("--out", type=Path, default=Path(__file__).resolve().parent)
    parser.add_argument(
        "--f16-tolerance-check",
        action="store_true",
        help="also run the f32 case with every input cast through f16 and "
        "back, printing the max abs diff against the f32 goldens (for the "
        "README's tolerance table); writes nothing extra to disk",
    )
    args = parser.parse_args()

    torch.manual_seed(0)
    digest = hashlib.sha256(args.adapter.read_bytes()).hexdigest()

    arrays, meta = capture(args.pulid_repo, args.adapter, cast_f16_inputs=False)
    meta["provenance"] = {
        "source": "ToTheBeginning/PuLID pulid/encoders_transformer.py::IDFormer, "
        "loaded from pulid_v1.1.safetensors id_adapter.* tensors",
        "adapter_file": args.adapter.name,
        "adapter_sha256": digest,
        "torch": torch.__version__,
        "dtype": "float32",
    }

    args.out.mkdir(parents=True, exist_ok=True)
    save_file(
        {k: v.contiguous() for k, v in arrays.items()},
        str(args.out / "idformer_goldens.safetensors"),
    )
    (args.out / "idformer_goldens.json").write_text(json.dumps(meta, indent=2) + "\n")
    for name, tensor in sorted(arrays.items()):
        print(f"{name:36s} {tuple(tensor.shape)} {tensor.dtype}")

    if args.f16_tolerance_check:
        f16_arrays, _ = capture(args.pulid_repo, args.adapter, cast_f16_inputs=True)
        print("\nf32 vs f16-round-tripped-inputs, max abs diff:")
        for key in ("idformer.single.output", "idformer.uncond.output", "idformer.two_image.output"):
            a = arrays[key]
            b = f16_arrays[key]
            diff = (a - b).abs().max().item()
            peak = a.abs().max().item()
            print(f"  {key:28s} max_abs={diff:.6e}  (peak {peak:.3f}, rel {diff / peak:.3e})")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
