#!/usr/bin/env bash
# Sourced, never executed: the layout of a Linux CUDA release archive and the
# one way a CUDA-linked release binary is EXECUTED on a host with no NVIDIA
# driver (a CI runner). Shared by scripts/package-cuda-release-archive.sh,
# which stages the archive, and scripts/verify-cuda-release-binary.sh, which
# refuses an archive that disagrees with it.
#
# An archive holds the binary and the shell completion scripts generated from
# that same binary at release time:
#
#   mold
#   completions/mold.bash
#   completions/_mold
#   completions/mold.fish
#
# The completions ride inside the archive because a packager must never have
# to RUN the payload: `mold` links the CUDA 12 runtime, and the AUR recipe used
# to execute it under fakeroot to generate these — which failed with
# `libcudart.so.12: cannot open shared object file` on a host that had no
# such library on its loader path (#1742). Each script is generated by invoking
# the binary THROUGH PATH so argv[0] is `mold`, and the scripts call back
# through the user's PATH at runtime instead of a baked-in build path.

# `<shell>:<archive path>` — the shells that have a system-wide completion
# directory on Linux, in the order they are packed.
MOLD_RELEASE_COMPLETIONS=(
  "bash:completions/mold.bash"
  "zsh:completions/_mold"
  "fish:completions/mold.fish"
)

# Every member of a release archive, binary first.
mold_release_archive_members() {
  local entry
  printf '%s\n' mold
  for entry in "${MOLD_RELEASE_COMPLETIONS[@]}"; do
    printf '%s\n' "${entry#*:}"
  done
}

# Print the LD_LIBRARY_PATH under which BINARY loads on this host without a
# GPU: the ambient value, plus a scratch directory holding the toolkit's
# `libcuda.so` stub as `libcuda.so.1` when `ldd` reports the driver library
# missing. Fails when the driver is absent and no toolkit stub can stand in.
mold_cuda_gpuless_loader_path() {
  local binary="$1"
  local scratch_dir="$2"
  local loader_path="${LD_LIBRARY_PATH:-}"
  local cuda_stub="" candidate

  if ldd "$binary" \
    | grep -Eq '^([[:space:]]*)libcuda\.so[^[:space:]]* => not found'; then
    for candidate in \
      /usr/local/cuda/lib64/stubs/libcuda.so \
      /opt/cuda/lib64/stubs/libcuda.so; do
      if [[ -f "$candidate" ]]; then
        cuda_stub="$candidate"
        break
      fi
    done
    if [[ -z "$cuda_stub" ]]; then
      echo "libcuda is unavailable and no CUDA toolkit loader stub was found" >&2
      return 1
    fi
    ln -sfn "$cuda_stub" "$scratch_dir/libcuda.so.1"
    loader_path="$scratch_dir${loader_path:+:$loader_path}"
  fi
  printf '%s\n' "$loader_path"
}

# Generate the completion script for SHELL from the binary named `mold` in
# BIN_DIR, invoked through PATH under LOADER_PATH, into OUTPUT. Refuses an
# empty script and one that names BIN_DIR, which would be a baked-in path.
mold_generate_release_completion() {
  local bin_dir="$1"
  local loader_path="$2"
  local shell="$3"
  local output="$4"

  [[ -x "$bin_dir/mold" ]] \
    || { echo "no executable mold in $bin_dir" >&2; return 1; }
  PATH="$bin_dir:$PATH" LD_LIBRARY_PATH="$loader_path" \
    mold completions "$shell" >"$output" \
    || { echo "mold completions $shell failed" >&2; return 1; }
  [[ -s "$output" ]] \
    || { echo "mold completions $shell produced an empty script" >&2; return 1; }
  if grep -Fq -- "$bin_dir" "$output"; then
    echo "mold completions $shell baked the staging path into the script" >&2
    return 1
  fi
}
