#!/usr/bin/env python3
"""Load PTX extracted from an exact Mold executable through the CUDA driver.

CUDA_FORCE_PTX_JIT affects NVIDIA runtime libraries as well as Mold kernels and
can fail during cuBLAS initialization before Mold PTX is reached. This probe
instead extracts complete entry modules from the named executable and submits
those exact bytes to cuModuleLoadData on the CUDA_VISIBLE_DEVICES device 0.
"""

from __future__ import annotations

import argparse
import ctypes
import ctypes.util
import hashlib
import json
import re
import sys
from pathlib import Path

CUDA_SUCCESS = 0
CUDA_ERROR_NO_BINARY_FOR_GPU = 209
CUDA_ERROR_INVALID_PTX = 218
INCOMPATIBLE_RESULTS = {
    CUDA_ERROR_NO_BINARY_FOR_GPU,
    CUDA_ERROR_INVALID_PTX,
}
VERSION_DIRECTIVE_RE = re.compile(rb"(?m)^[ \t]*\.version\b([^\r\n]*)")
VERSION_OPERAND_RE = re.compile(rb"^[ \t]+[0-9]+(?:\.[0-9]+)?[ \t]*$")
TARGET_DIRECTIVE_RE = re.compile(rb"(?m)^[ \t]*\.target[ \t]+([^\r\n]+)")
TARGET_ARCHITECTURE_RE = re.compile(rb"sm_([0-9]+)")
TARGET_PLATFORM_OPTIONS = {
    b"texmode_unified",
    b"texmode_independent",
    b"debug",
    b"map_f64_to_f32",
}
ADDRESS_DIRECTIVE_RE = re.compile(
    rb"(?m)^[ \t]*\.address_size[ \t]+([^\r\n]+)"
)
ADDRESS_OPERAND_RE = re.compile(rb"^(?:32|64)[ \t]*$")
ENTRY_DIRECTIVE_RE = re.compile(
    rb"(?m)^[ \t]*(?:\.visible[ \t]+)?\.entry\b"
)
ASCII_SPAN_RE = re.compile(rb"[\t\r\n\x20-\x7e]+")
PTX_GENERATOR_PREAMBLE_RE = re.compile(
    rb"(?m)^// Generated by (?:NVIDIA NVVM Compiler|LLVM NVPTX Back-End)[^\r\n]*"
)


def fail(message: str) -> None:
    print(f"embedded PTX probe: {message}", file=sys.stderr)
    raise SystemExit(1)


def sha256_bytes(value: bytes) -> str:
    return hashlib.sha256(value).hexdigest()


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def parse_target_operand(raw_directive: bytes) -> tuple[str | None, str]:
    """Return a normalized sm target and the printable raw operand."""

    printable = raw_directive.decode("ascii", "replace").strip()
    specifiers = [
        specifier.strip() for specifier in raw_directive.strip().split(b",")
    ]
    if not specifiers or any(not specifier for specifier in specifiers):
        return None, printable
    match = TARGET_ARCHITECTURE_RE.fullmatch(specifiers[0])
    if match is None:
        return None, printable
    options = specifiers[1:]
    if (
        any(option not in TARGET_PLATFORM_OPTIONS for option in options)
        or len(options) != len(set(options))
        or (
            b"texmode_unified" in options
            and b"texmode_independent" in options
        )
    ):
        return None, printable
    return specifiers[0].decode("ascii"), printable


def mask_ptx_non_code(segment: bytes) -> tuple[bytes, list[dict[str, object]]]:
    """Mask PTX comments and strings while preserving offsets and newlines."""

    view = bytearray(segment)
    errors: list[dict[str, object]] = []
    state = "code"
    state_start = 0
    escaped = False
    index = 0

    def mask(position: int) -> None:
        if view[position] not in (ord("\n"), ord("\r")):
            view[position] = ord(" ")

    while index < len(segment):
        byte = segment[index]
        following = segment[index + 1] if index + 1 < len(segment) else None

        if state == "code":
            if byte == ord("/") and following == ord("/"):
                state = "line_comment"
                state_start = index
                mask(index)
                mask(index + 1)
                index += 2
                continue
            if byte == ord("/") and following == ord("*"):
                state = "block_comment"
                state_start = index
                mask(index)
                mask(index + 1)
                index += 2
                continue
            if byte == ord("*") and following == ord("/"):
                errors.append(
                    {
                        "offset": index,
                        "reason": "block comment closes without opening",
                    }
                )
                mask(index)
                mask(index + 1)
                index += 2
                continue
            if byte == ord('"'):
                state = "string"
                state_start = index
                escaped = False
                mask(index)
                index += 1
                continue
            index += 1
            continue

        if state == "line_comment":
            if byte in (ord("\n"), ord("\r")):
                state = "code"
            else:
                mask(index)
            index += 1
            continue

        if state == "block_comment":
            if byte == ord("*") and following == ord("/"):
                mask(index)
                mask(index + 1)
                state = "code"
                index += 2
            else:
                mask(index)
                index += 1
            continue

        if state == "string":
            if byte in (ord("\n"), ord("\r")):
                errors.append(
                    {
                        "offset": state_start,
                        "reason": "string literal is not closed",
                    }
                )
                state = "code"
                escaped = False
                index += 1
                continue
            mask(index)
            if escaped:
                escaped = False
            elif byte == ord("\\"):
                escaped = True
            elif byte == ord('"'):
                state = "code"
            index += 1

    if state == "block_comment":
        errors.append(
            {
                "offset": state_start,
                "reason": "block comment is not closed",
            }
        )
    elif state == "string":
        errors.append(
            {
                "offset": state_start,
                "reason": "string literal is not closed",
            }
        )
    return bytes(view), errors


def ptx_lexical_regions(data: bytes):
    """Yield bounded ASCII regions without crossing generated PTX constants."""

    for span_match in ASCII_SPAN_RE.finditer(data):
        segment = span_match.group(0)
        if VERSION_DIRECTIVE_RE.search(segment) is None:
            continue
        preamble_starts = [
            match.start()
            for match in PTX_GENERATOR_PREAMBLE_RE.finditer(segment)
        ]
        boundaries = sorted({0, *preamble_starts, len(segment)})
        for start, end in zip(boundaries, boundaries[1:]):
            if start != end:
                yield span_match.start() + start, segment[start:end]


def extract_entry_modules(data: bytes) -> dict[str, object]:
    """Inventory self-contained first-entry PTX candidates in an exact artifact.

    Rust stores PTX as string data without a guaranteed NUL terminator in the
    final ELF. Starting at each `.version`, retain the header and first complete
    `.entry` body. Most Candle modules are self-contained at that boundary; the
    driver tries candidates in order because an entry may reference a helper
    function that appears later in its original module.

    Comments and strings are masked in a same-offset lexical view before any
    directive or brace is interpreted. Generated NVVM preambles bound PTX
    constants that the linker concatenates directly with unrelated printable
    Rust strings. Target-like text outside a complete `.version`/`.target`/
    `.address_size`/`.entry` module is ignored. Conversely, every real version
    region is inventoried as complete, malformed, or incomplete so release
    verification cannot silently lose a later module.
    """

    candidates: list[dict[str, object]] = []
    malformed_modules: list[dict[str, object]] = []
    incomplete_modules: list[dict[str, object]] = []
    seen_hashes: set[str] = set()

    # PTX source is contiguous ASCII. Splitting first avoids copying an entire
    # large ELF merely to mask comments, and prevents a random binary `/*`
    # sequence from changing lexical state across unrelated sections.
    for segment_start, segment in ptx_lexical_regions(data):
        raw_version_matches = list(VERSION_DIRECTIVE_RE.finditer(segment))
        if not raw_version_matches:
            continue
        code, lexical_errors = mask_ptx_non_code(segment)
        version_matches = list(VERSION_DIRECTIVE_RE.finditer(code))
        code_version_offsets = {match.start() for match in version_matches}
        hidden_version_offsets = [
            segment_start + match.start()
            for match in raw_version_matches
            if match.start() not in code_version_offsets
        ]

        # Lexical failures are structural failures for the complete bounded
        # region. They must remain visible even when they occur after the end
        # of an otherwise complete first entry, or when they mask every later
        # `.version` so the code view has no version match to iterate.
        for error in lexical_errors:
            incomplete_modules.append(
                {
                    "offset": segment_start + int(error["offset"]),
                    "reason": error["reason"],
                    "hidden_version_offsets": [
                        offset
                        for offset in hidden_version_offsets
                        if offset >= segment_start + int(error["offset"])
                    ],
                }
            )

        for match_index, version_match in enumerate(version_matches):
            start = version_match.start()
            search_end = (
                version_matches[match_index + 1].start()
                if match_index + 1 < len(version_matches)
                else len(segment)
            )
            global_start = segment_start + start
            if VERSION_OPERAND_RE.fullmatch(version_match.group(1)) is None:
                malformed_modules.append(
                    {
                        "offset": global_start,
                        "reason": "malformed version directive",
                        "version_directive": version_match.group(1)
                        .decode("ascii", "replace")
                        .strip(),
                    }
                )
                continue
            entry_match = ENTRY_DIRECTIVE_RE.search(code, start, search_end)
            if entry_match is None:
                incomplete_modules.append(
                    {
                        "offset": global_start,
                        "reason": "missing entry",
                    }
                )
                continue

            entry = entry_match.start()
            target_matches = list(
                TARGET_DIRECTIVE_RE.finditer(code, start, search_end)
            )
            if not target_matches:
                incomplete_modules.append(
                    {
                        "offset": global_start,
                        "reason": "missing target directive",
                    }
                )
                continue
            if len(target_matches) != 1:
                malformed_modules.append(
                    {
                        "offset": global_start,
                        "reason": "duplicate target directives",
                        "target_directives": [
                            match.group(1).decode("ascii", "replace").strip()
                            for match in target_matches
                        ],
                    }
                )
                continue
            target_match = target_matches[0]
            target, raw_target = parse_target_operand(target_match.group(1))
            if target is None:
                malformed_modules.append(
                    {
                        "offset": global_start,
                        "reason": "malformed target directive",
                        "target_directive": raw_target,
                    }
                )
                continue
            if target_match.start() > entry:
                malformed_modules.append(
                    {
                        "offset": global_start,
                        "reason": "target directive follows entry",
                        "target": target,
                    }
                )
                continue

            address_matches = list(
                ADDRESS_DIRECTIVE_RE.finditer(code, start, entry)
            )
            if not address_matches:
                incomplete_modules.append(
                    {
                        "offset": global_start,
                        "reason": "missing address_size",
                        "target": target,
                    }
                )
                continue
            if len(address_matches) != 1:
                malformed_modules.append(
                    {
                        "offset": global_start,
                        "reason": "duplicate address_size directives",
                        "target": target,
                    }
                )
                continue
            address_match = address_matches[0]
            if ADDRESS_OPERAND_RE.fullmatch(address_match.group(1).strip()) is None:
                malformed_modules.append(
                    {
                        "offset": global_start,
                        "reason": "malformed address_size directive",
                        "target": target,
                    }
                )
                continue
            if target_match.start() > address_match.start():
                malformed_modules.append(
                    {
                        "offset": global_start,
                        "reason": "target directive follows address_size",
                        "target": target,
                    }
                )
                continue

            opening_brace = code.find(b"{", entry_match.end(), search_end)
            if opening_brace < 0:
                incomplete_modules.append(
                    {
                        "offset": global_start,
                        "reason": "entry has no body",
                        "target": target,
                    }
                )
                continue

            depth = 0
            end = None
            for index in range(opening_brace, search_end):
                byte = code[index]
                if byte == ord("{"):
                    depth += 1
                elif byte == ord("}"):
                    depth -= 1
                    if depth == 0:
                        end = index + 1
                        break
            if end is None:
                incomplete_modules.append(
                    {
                        "offset": global_start,
                        "reason": "entry body is incomplete",
                        "target": target,
                    }
                )
                continue

            ptx = segment[start:end] + b"\n"
            ptx_sha256 = sha256_bytes(ptx)
            if ptx_sha256 in seen_hashes:
                continue
            seen_hashes.add(ptx_sha256)
            candidates.append(
                {
                    "offset": global_start,
                    "length": len(ptx),
                    "target": target,
                    "ptx_sha256": ptx_sha256,
                    "_ptx": ptx,
                }
            )

    return {
        "candidates": candidates,
        "malformed_modules": malformed_modules,
        "incomplete_modules": incomplete_modules,
        "observed_targets": sorted(
            {candidate["target"] for candidate in candidates}
        ),
    }


class CudaDriver:
    def __init__(self) -> None:
        library = ctypes.util.find_library("cuda") or "libcuda.so.1"
        try:
            self.lib = ctypes.CDLL(library)
        except OSError as error:
            fail(f"cannot load CUDA driver library: {error}")

        self.lib.cuInit.argtypes = [ctypes.c_uint]
        self.lib.cuInit.restype = ctypes.c_int
        self.lib.cuDeviceGet.argtypes = [ctypes.POINTER(ctypes.c_int), ctypes.c_int]
        self.lib.cuDeviceGet.restype = ctypes.c_int
        self.lib.cuCtxCreate_v2.argtypes = [
            ctypes.POINTER(ctypes.c_void_p),
            ctypes.c_uint,
            ctypes.c_int,
        ]
        self.lib.cuCtxCreate_v2.restype = ctypes.c_int
        self.lib.cuCtxDestroy_v2.argtypes = [ctypes.c_void_p]
        self.lib.cuCtxDestroy_v2.restype = ctypes.c_int
        self.lib.cuModuleLoadData.argtypes = [
            ctypes.POINTER(ctypes.c_void_p),
            ctypes.c_void_p,
        ]
        self.lib.cuModuleLoadData.restype = ctypes.c_int
        self.lib.cuModuleUnload.argtypes = [ctypes.c_void_p]
        self.lib.cuModuleUnload.restype = ctypes.c_int
        self.lib.cuGetErrorName.argtypes = [
            ctypes.c_int,
            ctypes.POINTER(ctypes.c_char_p),
        ]
        self.lib.cuGetErrorName.restype = ctypes.c_int

        result = self.lib.cuInit(0)
        if result != CUDA_SUCCESS:
            fail(f"cuInit failed: {self.error_name(result)} ({result})")
        device = ctypes.c_int()
        result = self.lib.cuDeviceGet(ctypes.byref(device), 0)
        if result != CUDA_SUCCESS:
            fail(f"cuDeviceGet(0) failed: {self.error_name(result)} ({result})")
        self.context = ctypes.c_void_p()
        result = self.lib.cuCtxCreate_v2(
            ctypes.byref(self.context),
            0,
            device,
        )
        if result != CUDA_SUCCESS:
            fail(f"cuCtxCreate_v2 failed: {self.error_name(result)} ({result})")

    def error_name(self, result: int) -> str:
        name = ctypes.c_char_p()
        if self.lib.cuGetErrorName(result, ctypes.byref(name)) == CUDA_SUCCESS and name.value:
            return name.value.decode("ascii", "replace")
        return f"CUDA_ERROR_{result}"

    def load(self, ptx: bytes) -> tuple[int, str]:
        source = ctypes.create_string_buffer(ptx + b"\0")
        module = ctypes.c_void_p()
        result = self.lib.cuModuleLoadData(
            ctypes.byref(module),
            ctypes.cast(source, ctypes.c_void_p),
        )
        if result == CUDA_SUCCESS:
            self.lib.cuModuleUnload(module)
        return result, self.error_name(result)

    def close(self) -> None:
        if self.context:
            self.lib.cuCtxDestroy_v2(self.context)
            self.context = ctypes.c_void_p()


def public_candidate(candidate: dict[str, object]) -> dict[str, object]:
    return {key: value for key, value in candidate.items() if key != "_ptx"}


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("binary", type=Path)
    parser.add_argument("compute_cap", help="numeric compute capability, for example 86")
    parser.add_argument(
        "--extract-only",
        action="store_true",
        help="validate and describe embedded PTX without opening CUDA",
    )
    parser.add_argument(
        "--expect-incompatible",
        action="store_true",
        help="pass only when every candidate is rejected as incompatible",
    )
    args = parser.parse_args()

    if not re.fullmatch(r"[0-9]+", args.compute_cap):
        fail("compute_cap must be numeric, for example 86")
    if not args.binary.is_file():
        fail(f"binary does not exist: {args.binary}")
    if args.extract_only and args.expect_incompatible:
        fail("--extract-only and --expect-incompatible cannot be combined")

    data = args.binary.read_bytes()
    inventory = extract_entry_modules(data)
    candidates = inventory["candidates"]
    malformed_modules = inventory["malformed_modules"]
    incomplete_modules = inventory["incomplete_modules"]
    observed_targets = inventory["observed_targets"]
    expected_target = f"sm_{args.compute_cap}"
    if malformed_modules:
        fail(f"malformed embedded PTX modules: {malformed_modules}")
    if incomplete_modules:
        fail(f"incomplete embedded PTX modules: {incomplete_modules}")
    if observed_targets != [expected_target]:
        rendered = ", ".join(observed_targets) if observed_targets else "none"
        fail(
            f"complete embedded PTX target set is {{{rendered}}}; "
            f"required set is {{{expected_target}}}"
        )
    expected_candidates = [
        candidate for candidate in candidates if candidate["target"] == expected_target
    ]
    if not expected_candidates:
        fail(f"no complete embedded {expected_target} PTX entry modules found")

    result: dict[str, object] = {
        "artifact_path": str(args.binary.resolve()),
        "artifact_sha256": sha256_file(args.binary),
        "expected_target": expected_target,
        "observed_targets": observed_targets,
        "candidate_count": len(expected_candidates),
        "candidates": [
            public_candidate(candidate) for candidate in expected_candidates
        ],
        "malformed_modules": malformed_modules,
        "incomplete_modules": incomplete_modules,
        "attempts": [],
        "loaded": False,
        "expect_incompatible": args.expect_incompatible,
    }
    if args.extract_only:
        print(json.dumps(result, sort_keys=True))
        return 0

    driver = CudaDriver()
    try:
        attempts: list[dict[str, object]] = []
        for candidate in expected_candidates:
            cuda_result, cuda_error_name = driver.load(candidate["_ptx"])  # type: ignore[arg-type]
            attempt = {
                **public_candidate(candidate),
                "cuda_result": cuda_result,
                "cuda_error_name": cuda_error_name,
                "loaded": cuda_result == CUDA_SUCCESS,
            }
            attempts.append(attempt)
            if cuda_result == CUDA_SUCCESS:
                result["loaded"] = True
                if not args.expect_incompatible:
                    break
        result["attempts"] = attempts
    finally:
        driver.close()

    print(json.dumps(result, sort_keys=True))
    if args.expect_incompatible:
        attempts = result["attempts"]
        return int(
            bool(result["loaded"])
            or not attempts
            or any(
                attempt["cuda_result"] not in INCOMPATIBLE_RESULTS
                for attempt in attempts  # type: ignore[union-attr]
            )
        )
    return 0 if result["loaded"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
