#!/usr/bin/env bash
set -euo pipefail

if [[ $# -lt 2 || $# -gt 3 ]]; then
  echo "usage: $0 <binary> <compute-capability> [archive.tar.gz]" >&2
  exit 64
fi

binary="$1"
compute_cap="$2"
archive="${3:-}"
repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# shellcheck source=scripts/lib/cuda-release-archive.sh
source "$repo_root/scripts/lib/cuda-release-archive.sh"
ptx_probe="$repo_root/scripts/probe-cuda-embedded-ptx.py"
h3_release_exclusion="$repo_root/scripts/verify-h3-release-exclusion.sh"

[[ "$compute_cap" =~ ^[0-9]+$ ]] \
  || { echo "compute capability must be numeric: $compute_cap" >&2; exit 64; }
[[ -x "$binary" ]] \
  || { echo "CUDA release binary is missing or not executable: $binary" >&2; exit 1; }

scratch_dir="$(mktemp -d)"
trap 'rm -rf "$scratch_dir"' EXIT

elf_header="$(readelf -h "$binary")"
grep -Eq 'Machine:[[:space:]]+Advanced Micro Devices X86-64' <<<"$elf_header" \
  || { echo "CUDA release binary is not Linux x86_64: $binary" >&2; exit 1; }

# Candle/cudarc embeds generated PTX as ordinary bytes in the final executable.
# The shared probe parses complete `.version`/`.target`/`.address_size`/`.entry`
# modules, ignores unrelated SPA/static strings, and requires the complete
# module-derived target set to be exactly the advertised release target. A
# future fat-PTX package must make that policy explicit in the shared parser.
[[ -x "$ptx_probe" ]] \
  || { echo "complete embedded PTX probe is missing: $ptx_probe" >&2; exit 1; }
"$ptx_probe" "$binary" "$compute_cap" --extract-only \
  >"$scratch_dir/embedded-ptx-inventory.json" \
  || { echo "CUDA release binary failed complete embedded PTX verification" >&2; exit 1; }

# nvml-wrapper loads the driver API at runtime and retains its symbol table in
# the stripped executable. Check a stable required entry point rather than a
# library filename: the wrapper does not retain that filename in Mold's final
# link, while this symbol disappears when the NVML feature is absent.
grep -aFq 'nvmlDeviceGetCount_v2' "$binary" \
  || { echo "CUDA release binary does not include NVML loader support" >&2; exit 1; }

ldd_output="$(ldd "$binary")"
unresolved="$(
  printf '%s\n' "$ldd_output" \
    | awk '/not found/ { print $1 }' \
    | grep -Ev '^(libcuda|libnvidia-ml)\.so' \
    || true
)"
if [[ -n "$unresolved" ]]; then
  echo "CUDA release binary has unexpected unresolved libraries:" >&2
  echo "$unresolved" >&2
  exit 1
fi

loader_path="$(mold_cuda_gpuless_loader_path "$binary" "$scratch_dir")"

LD_LIBRARY_PATH="$loader_path" "$binary" version >/dev/null \
  || { echo "CUDA release binary failed its GPU-less loader smoke" >&2; exit 1; }

[[ -x "$h3_release_exclusion" ]] \
  || { echo "MiniMax H3 release exclusion verifier is missing: $h3_release_exclusion" >&2; exit 1; }
"$h3_release_exclusion" "$binary" >/dev/null

if [[ -n "$archive" ]]; then
  [[ -f "$archive" ]] \
    || { echo "CUDA release archive is missing: $archive" >&2; exit 1; }
  [[ "$(tar -tzf "$archive" | sort)" == "$(mold_release_archive_members | sort)" ]] \
    || { echo "CUDA release archive must contain exactly mold and its shell completions" >&2; exit 1; }

  extract_dir="$scratch_dir/archive"
  mkdir -p "$extract_dir"
  tar -xzf "$archive" -C "$extract_dir"
  cmp "$binary" "$extract_dir/mold" \
    || { echo "CUDA release archive does not contain the verified binary" >&2; exit 1; }

  # Each shipped completion script must be what the verified binary emits when
  # invoked as `mold` — the same binary, and no staging path baked in.
  regenerated_dir="$scratch_dir/regenerated"
  mkdir -p "$regenerated_dir"
  chmod 0755 "$extract_dir/mold"
  for entry in "${MOLD_RELEASE_COMPLETIONS[@]}"; do
    shell="${entry%%:*}"
    member="${entry#*:}"
    mold_generate_release_completion \
      "$extract_dir" "$loader_path" "$shell" "$regenerated_dir/$shell" \
      || { echo "CUDA release binary cannot regenerate its $shell completions" >&2; exit 1; }
    cmp -s "$regenerated_dir/$shell" "$extract_dir/$member" \
      || { echo "CUDA release archive $shell completions were not generated by the verified binary as mold" >&2; exit 1; }
  done
fi

echo "verified CUDA sm_${compute_cap} release binary${archive:+ and archive}"
