#[cfg(test)]
pub(crate) static ENV_LOCK: std::sync::Mutex<()> = std::sync::Mutex::new(());

/// A minimal, fully-populated [`crate::types::GenerateRequest`] for tests that
/// only care about one field. Kept here so the exhaustive struct literal lives
/// in one place instead of being copied into every test module.
#[cfg(test)]
pub(crate) fn minimal_generate_request(model: &str) -> crate::types::GenerateRequest {
    crate::types::GenerateRequest {
        title: None,
        source_fit: None,
        hdr_exr_dir: None,
        hdr_exr_full_float: false,
        guidance_overrides: None,
        sample_shift: None,
        distill_strength_high: None,
        distill_strength_low: None,
        prompt: "a red apple".to_string(),
        negative_prompt: None,
        model: model.to_string(),
        width: 1024,
        height: 1024,
        steps: 4,
        guidance: 0.0,
        seed: Some(42),
        batch_size: 1,
        output_format: Some(crate::types::OutputFormat::Png),
        embed_metadata: None,
        scheduler: None,
        cfg_plus: None,
        source_image: None,
        source_image_name: None,
        edit_images: None,
        references: None,
        strength: 0.75,
        mask_image: None,
        control_image: None,
        control_model: None,
        control_scale: 1.0,
        expand: None,
        original_prompt: None,
        prompt_transform: None,
        batch_id: None,
        batch_index: None,
        batch_count: None,
        lora: None,
        frames: None,
        fps: None,
        upscale_model: None,
        gif_preview: false,
        enable_audio: None,
        audio_file: None,
        audio_file_path: None,
        source_video: None,
        source_video_path: None,
        extend_video: None,
        extend_video_path: None,
        extend_overlap_frames: None,
        keyframes: None,
        pipeline: None,
        ic_lora_control: None,
        loras: None,
        retake_range: None,
        spatial_upscale: None,
        temporal_upscale: None,
        placement: None,
        id_image: None,
        id_image_name: None,
        id_weight: None,
        id_start_step: None,
    }
}
