//! Device-resident MiniMax H3 Turbo LoRA deltas and their parallel-branch
//! forward.
//!
//! # Why a parallel branch is exact here
//!
//! The compact checkpoint stores each block linear as INT8 in a *rotated*
//! basis: `Q ~ quant(W_orig · H)`, where `H` is the block-diagonal 256-wide
//! regular Hadamard generated by `comfy_quant::regular_hadamard`. That
//! rotation is applied on the **input-feature axis** and `H = Hᵀ`, `H·H = I`,
//! so it cancels: `H3ComfyInt8ConvRotLinear::dequantize_weight` is documented
//! as reconstructing "the dense weight in the original, unrotated basis", and
//! the production `forward_reference` rotates the *activation* by the same `H`
//! before the INT8 accumulation, which means **its output is already in the
//! original basis**.
//!
//! The Turbo adapters were trained against that original basis (their
//! `__metadata__` names `Comfy-Org/MiniMax-H3 minimax_h3_fl2va_bf16` as the
//! base model). Therefore
//!
//! ```text
//! y = int8_convrot_forward(x) + ((x @ Aᵀ) @ Bᵀ) · (alpha / rank)
//! ```
//!
//! is mathematically exact — no rotation math, no dequantize/merge/requantize
//! round trip, and no extra quantization error on the delta. Merging instead
//! would require a full-weight round trip *inside* the denoise loop and would
//! add requantization error to a distilled model with only 4–8 steps of budget
//! to recover in.
//!
//! The in-repo precedent for this shape is
//! `crates/mold-inference/src/flux/lora_bypass.rs`, which applies FLUX LoRAs
//! as a parallel low-rank branch over a quantized base rather than merging.
//!
//! # Fused Q/K/V is free
//!
//! `qkv_fusion` in the published metadata reads "block diagonal B; concat A;
//! alpha multiplied by 3": `A = concat(A_q, A_k, A_v)` at `[3r, in]` and `B`
//! is block-diagonal at `[3·out_head, 3r]` with two thirds structural zeros.
//! A plain `(x @ Aᵀ) @ Bᵀ` therefore produces the correct fused result — the
//! zeros perform the routing — and `alpha·3 / rank·3` leaves the scale
//! unchanged. No slice bookkeeping is needed, which is why nothing here
//! mirrors FLUX's `FusedSlice`.
//!
//! # Residency
//!
//! Every delta is loaded to the execution device once at transformer
//! construction and stays resident for the whole denoise. That is a
//! deliberate choice over streaming the per-block slice alongside block
//! streaming: the whole adapter is 1,956,118,528 bytes of BF16 (see
//! [`H3TurboLoraRuntime::device_bytes`]), roughly a tenth of the 20.97 GB
//! INT8 stack, while streaming it would add ~1.96 GB of host-to-device
//! traffic on *every* transformer evaluation and would have to interleave
//! with the "exactly one live main block" invariant. Residency costs a fixed
//! ~1.82 GiB and keeps the streaming contract untouched.
//!
//! Nothing here registers an inference engine, capability, catalog entry, or
//! download.

use std::collections::BTreeMap;
use std::fs::File;
use std::io::{Read, Seek, SeekFrom};
use std::path::Path;

use candle::{DType, Device, Tensor};

use super::comfy_dit::{H3ComfyInt8Cancellation, FILE_READ_CHUNK_BYTES};
use super::turbo_lora::{
    authenticate_h3_turbo_lora_adapter_retaining, H3TurboLoraContract, H3TurboLoraError,
    H3TurboLoraErrorCode, H3TurboLoraExpectation, H3TurboLoraModule, H3TurboLoraModuleKind,
    H3TurboLoraModuleScope, H3TurboLoraResult, H3TurboLoraTensorRef, H3TurboLoraTier,
};

fn failure(code: H3TurboLoraErrorCode, message: impl Into<String>) -> H3TurboLoraError {
    H3TurboLoraError {
        code,
        message: message.into(),
    }
}

/// One module's low-rank Turbo delta, applied as a parallel branch in the
/// original (unrotated) basis. It is never merged into an INT8 ConvRot weight.
///
/// The transposes are materialized once at construction: `down_t` is `Aᵀ` at
/// `[in, rank]` and `up_t` is `Bᵀ` at `[rank, out]`, so a forward is two
/// contiguous matmuls and one affine with no per-call transpose.
#[derive(Clone, Debug)]
pub struct H3TurboLoraDelta {
    down_t: Tensor,
    up_t: Tensor,
    scale: f64,
    rank: usize,
    in_features: usize,
    out_features: usize,
    device_bytes: u64,
}

impl H3TurboLoraDelta {
    /// Build from `A` at `[rank, in]` and `B` at `[out, rank]`, exactly the
    /// published `lora_A` / `lora_B` orientation.
    pub fn new(down: &Tensor, up: &Tensor, scale: f32) -> H3TurboLoraResult<Self> {
        let (rank, in_features) = down.dims2().map_err(|error| {
            failure(
                H3TurboLoraErrorCode::ShapeMismatch,
                format!("H3 Turbo lora_A must be rank 2: {error}"),
            )
        })?;
        let (out_features, up_rank) = up.dims2().map_err(|error| {
            failure(
                H3TurboLoraErrorCode::ShapeMismatch,
                format!("H3 Turbo lora_B must be rank 2: {error}"),
            )
        })?;
        if rank != up_rank {
            return Err(failure(
                H3TurboLoraErrorCode::ShapeMismatch,
                format!("H3 Turbo lora_A rank {rank} does not match lora_B rank {up_rank}"),
            ));
        }
        if rank == 0 || in_features == 0 || out_features == 0 {
            return Err(failure(
                H3TurboLoraErrorCode::ShapeMismatch,
                "H3 Turbo delta dimensions must all be positive",
            ));
        }
        if down.dtype() != up.dtype() {
            return Err(failure(
                H3TurboLoraErrorCode::DTypeMismatch,
                format!(
                    "H3 Turbo lora_A is {:?} but lora_B is {:?}",
                    down.dtype(),
                    up.dtype()
                ),
            ));
        }
        if !down.device().same_device(up.device()) {
            return Err(failure(
                H3TurboLoraErrorCode::ConfigMismatch,
                "H3 Turbo lora_A and lora_B must be resident on one device",
            ));
        }
        if !scale.is_finite() || scale <= 0.0 {
            return Err(failure(
                H3TurboLoraErrorCode::ScaleMismatch,
                format!("H3 Turbo delta scale {scale} must be finite and positive"),
            ));
        }
        let device_bytes = [down, up]
            .iter()
            .try_fold(0u64, |total, tensor| {
                tensor
                    .elem_count()
                    .checked_mul(tensor.dtype().size_in_bytes())
                    .and_then(|bytes| u64::try_from(bytes).ok())
                    .and_then(|bytes| total.checked_add(bytes))
            })
            .ok_or_else(|| {
                failure(
                    H3TurboLoraErrorCode::ConfigMismatch,
                    "H3 Turbo delta byte count overflows",
                )
            })?;
        let transpose = |tensor: &Tensor, label: &str| -> H3TurboLoraResult<Tensor> {
            tensor
                .t()
                .and_then(|value| value.contiguous())
                .map_err(|error| {
                    failure(
                        H3TurboLoraErrorCode::ConfigMismatch,
                        format!("H3 Turbo {label} could not be transposed: {error}"),
                    )
                })
        };
        Ok(Self {
            down_t: transpose(down, "lora_A")?,
            up_t: transpose(up, "lora_B")?,
            scale: f64::from(scale),
            rank,
            in_features,
            out_features,
            device_bytes,
        })
    }

    pub const fn rank(&self) -> usize {
        self.rank
    }

    pub const fn in_features(&self) -> usize {
        self.in_features
    }

    pub const fn out_features(&self) -> usize {
        self.out_features
    }

    pub const fn scale(&self) -> f64 {
        self.scale
    }

    /// Resident bytes of this delta's two matrices.
    pub const fn device_bytes(&self) -> u64 {
        self.device_bytes
    }

    pub fn dtype(&self) -> DType {
        self.down_t.dtype()
    }

    pub fn device(&self) -> &Device {
        self.down_t.device()
    }

    /// `((x @ Aᵀ) @ Bᵀ) · scale`, in `x`'s dtype and with `x`'s leading dims.
    pub fn delta(&self, x: &Tensor) -> candle::Result<Tensor> {
        let dims = x.dims();
        let last = *dims.last().ok_or_else(|| {
            candle::Error::Msg("MiniMax H3 Turbo delta input must have a last dimension".into())
        })?;
        if last != self.in_features {
            candle::bail!(
                "MiniMax H3 Turbo delta expects {} input features, got {last}",
                self.in_features
            )
        }
        let rows = dims[..dims.len() - 1].iter().product::<usize>();
        let flat = x.reshape((rows, self.in_features))?.contiguous()?;
        let (down_t, up_t) = if self.down_t.dtype() == flat.dtype() {
            (self.down_t.clone(), self.up_t.clone())
        } else {
            (
                self.down_t.to_dtype(flat.dtype())?,
                self.up_t.to_dtype(flat.dtype())?,
            )
        };
        let projected = flat.matmul(&down_t)?;
        let delta = projected.matmul(&up_t)?.affine(self.scale, 0.0)?;
        let mut shape = dims[..dims.len() - 1].to_vec();
        shape.push(self.out_features);
        delta.reshape(shape)
    }

    /// `base + delta(x)`. `base` must already be this module's base output.
    pub fn apply(&self, x: &Tensor, base: &Tensor) -> candle::Result<Tensor> {
        base.add(&self.delta(x)?)
    }
}

/// Optionally apply a delta to a base output; `None` is the identity, which is
/// what keeps an unadapted forward bit-identical.
pub(super) fn apply_optional_turbo_delta(
    delta: Option<&H3TurboLoraDelta>,
    input: &Tensor,
    base: Tensor,
) -> candle::Result<Tensor> {
    match delta {
        None => Ok(base),
        Some(delta) => delta.apply(input, &base),
    }
}

/// The four deltas overlaying one block's linears.
#[derive(Clone, Debug)]
pub struct H3TurboBlockDeltas {
    pub qkv: H3TurboLoraDelta,
    pub out: H3TurboLoraDelta,
    pub fc1: H3TurboLoraDelta,
    pub fc2: H3TurboLoraDelta,
}

impl H3TurboBlockDeltas {
    pub fn device_bytes(&self) -> u64 {
        self.qkv.device_bytes
            + self.out.device_bytes
            + self.fc1.device_bytes
            + self.fc2.device_bytes
    }

    /// The delta overlaying one of the four adapted linears.
    pub fn kind(&self, kind: H3TurboLoraModuleKind) -> &H3TurboLoraDelta {
        match kind {
            H3TurboLoraModuleKind::AttnQkvProj => &self.qkv,
            H3TurboLoraModuleKind::AttnOutProj => &self.out,
            H3TurboLoraModuleKind::MlpFc1 => &self.fc1,
            H3TurboLoraModuleKind::MlpFc2 => &self.fc2,
        }
    }
}

/// Refuse a Turbo overlay whose geometry or residency does not match the block
/// it is about to be attached to.
///
/// This runs at construction rather than at forward time so a mismatched
/// adapter fails before any denoise step is paid for.
pub(super) fn validate_turbo_block_shapes(
    deltas: &H3TurboBlockDeltas,
    hidden_size: usize,
    inner_dim: usize,
    ffn_hidden_size: usize,
    device: &Device,
) -> candle::Result<()> {
    let expected = [
        ("attn.qkv_proj", &deltas.qkv, hidden_size, 3 * inner_dim),
        ("attn.out_proj", &deltas.out, inner_dim, hidden_size),
        ("mlp.fc1", &deltas.fc1, hidden_size, 2 * ffn_hidden_size),
        ("mlp.fc2", &deltas.fc2, ffn_hidden_size, hidden_size),
    ];
    for (label, delta, in_features, out_features) in expected {
        if delta.in_features() != in_features || delta.out_features() != out_features {
            candle::bail!(
                "MiniMax H3 Turbo delta {label} is [{} -> {}], this block needs [{in_features} -> {out_features}]",
                delta.in_features(),
                delta.out_features()
            )
        }
        if !delta.device().same_device(device) {
            candle::bail!(
                "MiniMax H3 Turbo delta {label} is not resident on the block's execution device"
            )
        }
    }
    Ok(())
}

/// Every Turbo delta of one authenticated adapter, resident on the execution
/// device for the whole denoise.
#[derive(Clone, Debug)]
pub struct H3TurboLoraRuntime {
    tier: H3TurboLoraTier,
    adapter_identity_sha256: String,
    content_sha256: String,
    scale: f32,
    main_blocks: Vec<H3TurboBlockDeltas>,
    token_refiner_blocks: Vec<H3TurboBlockDeltas>,
    device_bytes: u64,
}

impl H3TurboLoraRuntime {
    pub fn tier(&self) -> H3TurboLoraTier {
        self.tier
    }

    /// The authenticated adapter identity, for a frozen execution plan that
    /// has to record which weights actually ran.
    pub fn adapter_identity_sha256(&self) -> &str {
        &self.adapter_identity_sha256
    }

    pub fn content_sha256(&self) -> &str {
        &self.content_sha256
    }

    /// The one `alpha / rank` every module agreed on.
    pub const fn scale(&self) -> f32 {
        self.scale
    }

    pub fn block_count(&self) -> usize {
        self.main_blocks.len()
    }

    pub fn token_refiner_block_count(&self) -> usize {
        self.token_refiner_blocks.len()
    }

    pub fn main_block(&self, index: usize) -> Option<&H3TurboBlockDeltas> {
        self.main_blocks.get(index)
    }

    pub fn token_refiner_block(&self, index: usize) -> Option<&H3TurboBlockDeltas> {
        self.token_refiner_blocks.get(index)
    }

    /// Exact resident device bytes of every `lora_A` / `lora_B` matrix.
    ///
    /// The 208 `alpha` scalars are folded into each delta's `scale` at load
    /// and never stay resident, so this is the adapter's payload minus
    /// `208 * 4` bytes.
    pub const fn device_bytes(&self) -> u64 {
        self.device_bytes
    }

    /// Build from an authenticated contract plus the descriptor the digest was
    /// computed over.
    pub fn from_authenticated(
        contract: &H3TurboLoraContract,
        file: &mut File,
        device: &Device,
        dtype: DType,
        cancellation: &dyn H3ComfyInt8Cancellation,
    ) -> H3TurboLoraResult<Self> {
        if !matches!(dtype, DType::BF16 | DType::F16 | DType::F32 | DType::F64) {
            return Err(failure(
                H3TurboLoraErrorCode::DTypeMismatch,
                format!("H3 Turbo runtime requires a floating compute dtype, got {dtype:?}"),
            ));
        }
        let inspection = contract.inspection();
        let data_start = 8u64.checked_add(inspection.header_len).ok_or_else(|| {
            failure(
                H3TurboLoraErrorCode::InvalidHeader,
                "H3 Turbo adapter data offset overflows",
            )
        })?;

        let mut main = BTreeMap::<usize, BTreeMap<H3TurboLoraModuleKind, H3TurboLoraDelta>>::new();
        let mut refiner =
            BTreeMap::<usize, BTreeMap<H3TurboLoraModuleKind, H3TurboLoraDelta>>::new();
        let mut device_bytes = 0u64;
        for module in inspection.modules.values() {
            cancellation_boundary(cancellation)?;
            let delta = load_module_delta(module, file, data_start, device, dtype, cancellation)?;
            device_bytes = device_bytes
                .checked_add(delta.device_bytes())
                .ok_or_else(|| {
                    failure(
                        H3TurboLoraErrorCode::ConfigMismatch,
                        "H3 Turbo resident byte count overflows",
                    )
                })?;
            let target = match module.scope {
                H3TurboLoraModuleScope::MainBlock(index) => main.entry(index).or_default(),
                H3TurboLoraModuleScope::TokenRefinerBlock(index) => {
                    refiner.entry(index).or_default()
                }
            };
            if target.insert(module.kind, delta).is_some() {
                return Err(failure(
                    H3TurboLoraErrorCode::ConfigMismatch,
                    format!("H3 Turbo module {:?} was resolved twice", module.name),
                ));
            }
        }

        Ok(Self {
            tier: contract.tier(),
            adapter_identity_sha256: contract.adapter_identity_sha256().to_owned(),
            content_sha256: contract.content_sha256().to_owned(),
            scale: inspection.scale,
            main_blocks: collect_contiguous_blocks(main, "main")?,
            token_refiner_blocks: collect_contiguous_blocks(refiner, "token refiner")?,
            device_bytes,
        })
    }

    /// Authenticate one published adapter and load every delta onto `device`.
    ///
    /// The tensors are read through the exact descriptor whose complete
    /// content digest was just verified, so the resident deltas are provably
    /// the reviewed bytes.
    pub fn open(
        path: &Path,
        tier: H3TurboLoraTier,
        device: &Device,
        dtype: DType,
        cancellation: &dyn H3ComfyInt8Cancellation,
    ) -> H3TurboLoraResult<Self> {
        Self::open_against(path, &tier.expectation(), tier, device, dtype, cancellation)
    }

    pub(crate) fn open_against(
        path: &Path,
        expectation: &H3TurboLoraExpectation,
        tier: H3TurboLoraTier,
        device: &Device,
        dtype: DType,
        cancellation: &dyn H3ComfyInt8Cancellation,
    ) -> H3TurboLoraResult<Self> {
        let (contract, mut file) =
            authenticate_h3_turbo_lora_adapter_retaining(path, expectation, tier, cancellation)?;
        Self::from_authenticated(&contract, &mut file, device, dtype, cancellation)
    }
}

fn cancellation_boundary(cancellation: &dyn H3ComfyInt8Cancellation) -> H3TurboLoraResult<()> {
    if cancellation.is_cancelled() {
        return Err(failure(
            H3TurboLoraErrorCode::Cancelled,
            "MiniMax H3 Turbo adapter load was cancelled",
        ));
    }
    Ok(())
}

fn collect_contiguous_blocks(
    blocks: BTreeMap<usize, BTreeMap<H3TurboLoraModuleKind, H3TurboLoraDelta>>,
    label: &str,
) -> H3TurboLoraResult<Vec<H3TurboBlockDeltas>> {
    let mut resolved = Vec::with_capacity(blocks.len());
    for (expected_index, (index, mut kinds)) in blocks.into_iter().enumerate() {
        if index != expected_index {
            return Err(failure(
                H3TurboLoraErrorCode::MissingModule,
                format!("H3 Turbo {label} block indices are not contiguous from zero"),
            ));
        }
        let mut take = |kind: H3TurboLoraModuleKind| -> H3TurboLoraResult<H3TurboLoraDelta> {
            kinds.remove(&kind).ok_or_else(|| {
                failure(
                    H3TurboLoraErrorCode::MissingModule,
                    format!("H3 Turbo {label} block {index} is missing {:?}", kind),
                )
            })
        };
        resolved.push(H3TurboBlockDeltas {
            qkv: take(H3TurboLoraModuleKind::AttnQkvProj)?,
            out: take(H3TurboLoraModuleKind::AttnOutProj)?,
            fc1: take(H3TurboLoraModuleKind::MlpFc1)?,
            fc2: take(H3TurboLoraModuleKind::MlpFc2)?,
        });
    }
    Ok(resolved)
}

fn load_module_delta(
    module: &H3TurboLoraModule,
    file: &mut File,
    data_start: u64,
    device: &Device,
    dtype: DType,
    cancellation: &dyn H3ComfyInt8Cancellation,
) -> H3TurboLoraResult<H3TurboLoraDelta> {
    let down = read_delta_tensor(
        &module.lora_a,
        file,
        data_start,
        device,
        dtype,
        cancellation,
    )?;
    let up = read_delta_tensor(
        &module.lora_b,
        file,
        data_start,
        device,
        dtype,
        cancellation,
    )?;
    let delta = H3TurboLoraDelta::new(&down, &up, module.scale)?;
    if delta.rank() != module.rank
        || delta.in_features() != module.in_features
        || delta.out_features() != module.out_features
    {
        return Err(failure(
            H3TurboLoraErrorCode::ShapeMismatch,
            format!(
                "H3 Turbo module {:?} loaded as rank {} [{} -> {}], contract says rank {} [{} -> {}]",
                module.name,
                delta.rank(),
                delta.in_features(),
                delta.out_features(),
                module.rank,
                module.in_features,
                module.out_features
            ),
        ));
    }
    Ok(delta)
}

fn read_delta_tensor(
    reference: &H3TurboLoraTensorRef,
    file: &mut File,
    data_start: u64,
    device: &Device,
    dtype: DType,
    cancellation: &dyn H3ComfyInt8Cancellation,
) -> H3TurboLoraResult<Tensor> {
    if reference.dtype != "BF16" {
        return Err(failure(
            H3TurboLoraErrorCode::DTypeMismatch,
            format!(
                "H3 Turbo tensor {:?} must be BF16 storage, found {}",
                reference.name, reference.dtype
            ),
        ));
    }
    let len =
        usize::try_from(reference.data_offsets[1] - reference.data_offsets[0]).map_err(|_| {
            failure(
                H3TurboLoraErrorCode::InvalidHeader,
                format!("H3 Turbo tensor {:?} is too large", reference.name),
            )
        })?;
    let start = data_start
        .checked_add(reference.data_offsets[0])
        .ok_or_else(|| {
            failure(
                H3TurboLoraErrorCode::InvalidHeader,
                format!("H3 Turbo tensor {:?} offset overflows", reference.name),
            )
        })?;
    file.seek(SeekFrom::Start(start)).map_err(|error| {
        failure(
            H3TurboLoraErrorCode::Io,
            format!(
                "failed to seek H3 Turbo tensor {:?}: {error}",
                reference.name
            ),
        )
    })?;
    let mut bytes = vec![0u8; len];
    let mut offset = 0usize;
    while offset < bytes.len() {
        cancellation_boundary(cancellation)?;
        let end = (offset + FILE_READ_CHUNK_BYTES).min(bytes.len());
        file.read_exact(&mut bytes[offset..end]).map_err(|error| {
            failure(
                H3TurboLoraErrorCode::Io,
                format!(
                    "failed to read H3 Turbo tensor {:?}: {error}",
                    reference.name
                ),
            )
        })?;
        offset = end;
    }
    let tensor = Tensor::from_raw_buffer(&bytes, DType::BF16, &reference.shape, &Device::Cpu)
        .and_then(|tensor| {
            if dtype == DType::BF16 {
                Ok(tensor)
            } else {
                tensor.to_dtype(dtype)
            }
        })
        .and_then(|tensor| tensor.to_device(device))
        .map_err(|error| {
            failure(
                H3TurboLoraErrorCode::Io,
                format!(
                    "failed to materialize H3 Turbo tensor {:?}: {error}",
                    reference.name
                ),
            )
        })?;
    Ok(tensor)
}

#[cfg(test)]
mod tests {
    use super::super::comfy_dit::H3ComfyNeverCancel;
    use super::super::turbo_lora::fixtures;
    use super::*;

    #[test]
    fn a_delta_computes_the_low_rank_product_with_its_scale() {
        let device = Device::Cpu;
        let down = Tensor::new(&[[1.0f32, 0.0, 2.0], [0.0, 3.0, -1.0]], &device).unwrap();
        let up = Tensor::new(
            &[[1.0f32, 2.0], [-1.0, 0.5], [0.0, 1.0], [4.0, 0.0]],
            &device,
        )
        .unwrap();
        let delta = H3TurboLoraDelta::new(&down, &up, 0.25).unwrap();
        assert_eq!(delta.rank(), 2);
        assert_eq!(delta.in_features(), 3);
        assert_eq!(delta.out_features(), 4);

        let x = Tensor::new(&[[1.0f32, 2.0, 3.0], [-1.0, 0.0, 0.5]], &device).unwrap();
        let observed = delta.delta(&x).unwrap().to_vec2::<f32>().unwrap();

        // Reference: x @ (scale * (B @ A))^T
        let merged = up.matmul(&down).unwrap().affine(0.25, 0.0).unwrap();
        let expected = x
            .matmul(&merged.t().unwrap().contiguous().unwrap())
            .unwrap()
            .to_vec2::<f32>()
            .unwrap();
        for (row, expected_row) in observed.iter().zip(expected.iter()) {
            for (value, expected_value) in row.iter().zip(expected_row.iter()) {
                assert!(
                    (value - expected_value).abs() < 1e-5,
                    "{value} {expected_value}"
                );
            }
        }
    }

    #[test]
    fn a_delta_rejects_inconsistent_shapes_dtypes_and_scales() {
        let device = Device::Cpu;
        let down = Tensor::zeros((2, 3), DType::F32, &device).unwrap();
        let up = Tensor::zeros((4, 3), DType::F32, &device).unwrap();
        assert_eq!(
            H3TurboLoraDelta::new(&down, &up, 1.0).unwrap_err().code,
            H3TurboLoraErrorCode::ShapeMismatch
        );

        let up = Tensor::zeros((4, 2), DType::F32, &device).unwrap();
        for scale in [0.0f32, -1.0, f32::NAN] {
            assert_eq!(
                H3TurboLoraDelta::new(&down, &up, scale).unwrap_err().code,
                H3TurboLoraErrorCode::ScaleMismatch
            );
        }

        let wide = Tensor::zeros((4, 2), DType::F64, &device).unwrap();
        assert_eq!(
            H3TurboLoraDelta::new(&down, &wide, 1.0).unwrap_err().code,
            H3TurboLoraErrorCode::DTypeMismatch
        );
    }

    /// A rank-`r` delta built from explicit matrices, for the fused-QKV proof.
    fn delta_of(down: &Tensor, up: &Tensor, scale: f32) -> H3TurboLoraDelta {
        H3TurboLoraDelta::new(down, up, scale).unwrap()
    }

    fn ramp(rows: usize, cols: usize, seed: usize, device: &Device) -> Tensor {
        let values = (0..rows * cols)
            .map(|index| ((index.wrapping_mul(37).wrapping_add(seed)) % 23) as f32 / 11.0 - 1.0)
            .collect::<Vec<_>>();
        Tensor::from_vec(values, (rows, cols), device).unwrap()
    }

    #[test]
    fn the_scale_is_alpha_over_rank_and_is_applied_linearly() {
        let device = Device::Cpu;
        let down = ramp(4, 6, 1, &device);
        let up = ramp(5, 4, 2, &device);
        let x = ramp(3, 6, 3, &device);

        // 8/128 and 24/384 are the published non-fused and fused alpha/rank
        // pairs; they must resolve to the identical scale.
        assert_eq!(8.0f32 / 128.0, 24.0f32 / 384.0);
        let unit = delta_of(&down, &up, 1.0).delta(&x).unwrap();
        for scale in [8.0f32 / 128.0, 128.0 / 128.0, 384.0 / 384.0, 0.5] {
            let scaled = delta_of(&down, &up, scale).delta(&x).unwrap();
            let expected = unit.affine(f64::from(scale), 0.0).unwrap();
            let observed = scaled.to_vec2::<f32>().unwrap();
            let expected = expected.to_vec2::<f32>().unwrap();
            for (row, expected_row) in observed.iter().zip(expected.iter()) {
                for (value, want) in row.iter().zip(expected_row.iter()) {
                    assert!((value - want).abs() < 1e-5, "{scale}: {value} vs {want}");
                }
            }
        }
    }

    #[test]
    fn fused_qkv_routing_equals_three_independent_deltas() {
        // `qkv_fusion` is "block diagonal B; concat A; alpha multiplied by 3".
        // Build that layout explicitly and prove the naive (x @ Aᵀ) @ Bᵀ
        // reproduces three independent rank-r deltas concatenated on the
        // output axis — which is why no FusedSlice bookkeeping is needed.
        let device = Device::Cpu;
        let rank = 2usize;
        let in_features = 5usize;
        let out_each = 3usize;
        let alpha = 4.0f32;
        let scale = alpha / rank as f32;

        let a = [
            ramp(rank, in_features, 11, &device),
            ramp(rank, in_features, 12, &device),
            ramp(rank, in_features, 13, &device),
        ];
        let b = [
            ramp(out_each, rank, 21, &device),
            ramp(out_each, rank, 22, &device),
            ramp(out_each, rank, 23, &device),
        ];

        // concat A on the rank axis
        let fused_a = Tensor::cat(&[&a[0], &a[1], &a[2]], 0).unwrap();
        assert_eq!(fused_a.dims(), &[3 * rank, in_features]);

        // block-diagonal B: [3*out_each, 3*rank] with two thirds zeros
        let zero = Tensor::zeros((out_each, rank), DType::F32, &device).unwrap();
        let rows = [
            Tensor::cat(&[&b[0], &zero, &zero], 1).unwrap(),
            Tensor::cat(&[&zero, &b[1], &zero], 1).unwrap(),
            Tensor::cat(&[&zero, &zero, &b[2]], 1).unwrap(),
        ];
        let fused_b = Tensor::cat(&[&rows[0], &rows[1], &rows[2]], 0).unwrap();
        assert_eq!(fused_b.dims(), &[3 * out_each, 3 * rank]);

        // alpha multiplied by three keeps alpha/rank unchanged
        let fused_scale = (alpha * 3.0) / (rank * 3) as f32;
        assert_eq!(fused_scale, scale);

        let x = ramp(4, in_features, 31, &device);
        let fused = delta_of(&fused_a, &fused_b, fused_scale)
            .delta(&x)
            .unwrap()
            .to_vec2::<f32>()
            .unwrap();

        let independent = (0..3)
            .map(|index| {
                delta_of(&a[index], &b[index], scale)
                    .delta(&x)
                    .unwrap()
                    .to_vec2::<f32>()
                    .unwrap()
            })
            .collect::<Vec<_>>();

        for row in 0..4 {
            for part in 0..3 {
                for column in 0..out_each {
                    let observed = fused[row][part * out_each + column];
                    let expected = independent[part][row][column];
                    assert!(
                        (observed - expected).abs() < 1e-5,
                        "row {row} part {part} col {column}: {observed} vs {expected}"
                    );
                }
            }
        }
    }

    #[test]
    fn a_delta_reshapes_batched_activations() {
        let device = Device::Cpu;
        let down = ramp(2, 4, 5, &device);
        let up = ramp(3, 2, 6, &device);
        let delta = delta_of(&down, &up, 0.25);
        let x = Tensor::from_vec(
            (0..2 * 5 * 4)
                .map(|index| index as f32 / 13.0)
                .collect::<Vec<_>>(),
            (2, 5, 4),
            &device,
        )
        .unwrap();
        let out = delta.delta(&x).unwrap();
        assert_eq!(out.dims(), &[2, 5, 3]);

        // Row-for-row agreement with the flattened computation.
        let flat = delta.delta(&x.reshape((10, 4)).unwrap()).unwrap();
        let batched = out.reshape((10, 3)).unwrap().to_vec2::<f32>().unwrap();
        let reference = flat.to_vec2::<f32>().unwrap();
        assert_eq!(batched, reference);
    }

    #[test]
    fn a_delta_refuses_an_input_width_it_was_not_built_for() {
        let device = Device::Cpu;
        let delta = delta_of(&ramp(2, 4, 1, &device), &ramp(3, 2, 2, &device), 1.0);
        assert!(delta.delta(&ramp(2, 5, 3, &device)).is_err());
    }

    /// The exact resident cost of a published adapter, derived from the pinned
    /// module geometry rather than restated.
    #[test]
    fn resident_device_bytes_are_the_published_payload_minus_the_alpha_scalars() {
        let expectation = H3TurboLoraTier::Fl2v8StepV10.expectation();
        let (modules, _) = super::super::turbo_lora::expected_turbo_modules(&expectation)
            .expect("published geometry");
        let mut matrix_elements = 0u64;
        for module in modules.values() {
            matrix_elements += (module.rank * module.in_features) as u64;
            matrix_elements += (module.out_features * module.rank) as u64;
        }
        let matrix_bytes = matrix_elements * 2; // BF16

        // Payload = every lora_A/lora_B byte plus one F32 alpha per module.
        assert_eq!(
            matrix_bytes + (modules.len() as u64) * 4,
            super::super::turbo_lora::H3_TURBO_LORA_PAYLOAD_BYTES
        );
        // 1,956,118,528 bytes = 1.8216 GiB stay resident for the whole denoise.
        assert_eq!(matrix_bytes, 1_956_118_528);
    }

    /// Rebuild one adapter matrix from the fixture generator, without reading
    /// the file, so the loaded tensor can be checked independently.
    fn expected_matrix(name: &str, rows: usize, cols: usize) -> Tensor {
        let values = (0..rows * cols)
            .map(|index| f32::from(half::bf16::from_f32(fixtures::weight_value(name, index))))
            .collect::<Vec<_>>();
        Tensor::from_vec(values, (rows, cols), &Device::Cpu).unwrap()
    }

    #[test]
    fn the_runtime_loads_every_delta_from_the_authenticated_descriptor() {
        let (_directory, path, pinned) = fixtures::pinned();
        let runtime = H3TurboLoraRuntime::open_against(
            &path,
            &pinned,
            H3TurboLoraTier::Fl2v8StepV10,
            &Device::Cpu,
            DType::F32,
            &H3ComfyNeverCancel,
        )
        .unwrap();

        assert_eq!(runtime.tier(), H3TurboLoraTier::Fl2v8StepV10);
        assert_eq!(runtime.block_count(), 2);
        assert_eq!(runtime.token_refiner_block_count(), 1);
        assert_eq!(runtime.scale(), 0.0625);
        assert_eq!(runtime.adapter_identity_sha256().len(), 64);
        assert_eq!(
            runtime.content_sha256(),
            pinned.content_sha256.as_deref().unwrap()
        );
        assert!(runtime.main_block(2).is_none());
        assert!(runtime.token_refiner_block(1).is_none());

        // Every module's geometry, including the fused Q/K/V triple rank.
        let block = runtime.main_block(0).unwrap();
        assert_eq!(block.qkv.rank(), 12);
        assert_eq!(block.qkv.in_features(), 256);
        assert_eq!(block.qkv.out_features(), 768);
        assert_eq!(block.out.rank(), 4);
        assert_eq!(block.fc1.out_features(), 512);
        assert_eq!(block.fc2.in_features(), 256);
        for kind in H3TurboLoraModuleKind::ALL {
            // alpha/rank is uniform: the fused module's tripled alpha cancels
            // against its tripled rank.
            assert_eq!(block.kind(kind).scale(), f64::from(runtime.scale()));
        }

        // Resident bytes are the sum of every matrix, and the block figure is
        // uniform across blocks.
        let per_block = block.device_bytes();
        assert_eq!(
            runtime.device_bytes(),
            per_block * 2 + runtime.token_refiner_block(0).unwrap().device_bytes()
        );
        assert_eq!(per_block, runtime.main_block(1).unwrap().device_bytes());

        // The loaded delta reproduces the reference built from the same
        // deterministic generator, proving the offsets and BF16 decode.
        let name = "diffusion_model.blocks.0.mlp.fc2";
        let down = expected_matrix(&format!("{name}.lora_A.weight"), 4, 256);
        let up = expected_matrix(&format!("{name}.lora_B.weight"), 256, 4);
        let reference = H3TurboLoraDelta::new(&down, &up, 0.0625).unwrap();
        let x = ramp(3, 256, 77, &Device::Cpu);
        let observed = block.fc2.delta(&x).unwrap().to_vec2::<f32>().unwrap();
        let expected = reference.delta(&x).unwrap().to_vec2::<f32>().unwrap();
        for (row, expected_row) in observed.iter().zip(expected.iter()) {
            for (value, want) in row.iter().zip(expected_row.iter()) {
                assert!((value - want).abs() < 1e-5, "{value} vs {want}");
            }
        }
    }

    #[test]
    fn the_runtime_refuses_to_load_without_an_authenticated_digest() {
        let (_directory, path, mut pinned) = fixtures::pinned();
        pinned.content_sha256 = None;
        let error = H3TurboLoraRuntime::open_against(
            &path,
            &pinned,
            H3TurboLoraTier::Fl2v8StepV10,
            &Device::Cpu,
            DType::F32,
            &H3ComfyNeverCancel,
        )
        .unwrap_err();
        assert_eq!(error.code, H3TurboLoraErrorCode::MissingContentPin);
    }

    #[test]
    fn the_runtime_requires_a_floating_compute_dtype() {
        let (_directory, path, pinned) = fixtures::pinned();
        let error = H3TurboLoraRuntime::open_against(
            &path,
            &pinned,
            H3TurboLoraTier::Fl2v8StepV10,
            &Device::Cpu,
            DType::U8,
            &H3ComfyNeverCancel,
        )
        .unwrap_err();
        assert_eq!(error.code, H3TurboLoraErrorCode::DTypeMismatch);
    }

    #[test]
    fn an_absent_delta_is_the_identity() {
        let device = Device::Cpu;
        let x = Tensor::new(&[[1.0f32, 2.0, 3.0]], &device).unwrap();
        let base = Tensor::new(&[[7.0f32, 8.0]], &device).unwrap();
        let passed = apply_optional_turbo_delta(None, &x, base.clone()).unwrap();
        assert_eq!(
            passed.to_vec2::<f32>().unwrap(),
            base.to_vec2::<f32>().unwrap()
        );
    }
}
