//! Device-resident MiniMax H3 Turbo LoRA deltas and their parallel-branch
//! forward.
//!
//! # Why a parallel branch is exact here
//!
//! The compact checkpoint stores each block linear as INT8 in a *rotated*
//! basis: `Q ~ quant(W_orig · H)`, where `H` is the block-diagonal 256-wide
//! regular Hadamard generated by `comfy_quant::regular_hadamard`. That
//! rotation is applied on the **input-feature axis** and `H = Hᵀ`, `H·H = I`,
//! so it cancels: `H3ComfyInt8ConvRotLinear::dequantize_weight` is documented
//! as reconstructing "the dense weight in the original, unrotated basis", and
//! the production `forward_reference` rotates the *activation* by the same `H`
//! before the INT8 accumulation, which means **its output is already in the
//! original basis**.
//!
//! The Turbo adapters were trained against that original basis (their
//! `__metadata__` names `Comfy-Org/MiniMax-H3 minimax_h3_fl2va_bf16` as the
//! base model). Therefore
//!
//! ```text
//! y = int8_convrot_forward(x) + ((x @ Aᵀ) @ Bᵀ) · (alpha / rank)
//! ```
//!
//! is mathematically exact — no rotation math, no dequantize/merge/requantize
//! round trip, and no extra quantization error on the delta. Merging instead
//! would require a full-weight round trip *inside* the denoise loop and would
//! add requantization error to a distilled model with only 4–8 steps of budget
//! to recover in.
//!
//! The in-repo precedent for this shape is
//! `crates/mold-inference/src/flux/lora_bypass.rs`, which applies FLUX LoRAs
//! as a parallel low-rank branch over a quantized base rather than merging.
//!
//! # Fused Q/K/V is free
//!
//! `qkv_fusion` in the published metadata reads "block diagonal B; concat A;
//! alpha multiplied by 3": `A = concat(A_q, A_k, A_v)` at `[3r, in]` and `B`
//! is block-diagonal at `[3·out_head, 3r]` with two thirds structural zeros.
//! A plain `(x @ Aᵀ) @ Bᵀ` therefore produces the correct fused result — the
//! zeros perform the routing — and `alpha·3 / rank·3` leaves the scale
//! unchanged. No slice bookkeeping is needed, which is why nothing here
//! mirrors FLUX's `FusedSlice`.
//!
//! # Residency
//!
//! CUDA loads every delta once and keeps the 1,956,118,528-byte adapter
//! resident. Metal shares memory with the host, so its correctness route keeps
//! only the 75,235,328-byte token-refiner slice resident and reads one main-
//! block slice through the same one-live-block lifetime as the INT8 base.
//!
//! Nothing here registers an inference engine, capability, catalog entry, or
//! download.

use std::collections::BTreeMap;
use std::fs::File;
use std::io::{Read, Seek, SeekFrom};
use std::path::Path;
use std::sync::{Arc, Mutex};

use candle::{DType, Device, DeviceLocation, Tensor};

use super::comfy_dit::{H3ComfyInt8Cancellation, H3OpenedFileIdentity, FILE_READ_CHUNK_BYTES};
use super::turbo_lora::{
    authenticate_h3_turbo_lora_adapter_retaining, H3TurboLoraContract, H3TurboLoraError,
    H3TurboLoraErrorCode, H3TurboLoraExpectation, H3TurboLoraModule, H3TurboLoraModuleKind,
    H3TurboLoraModuleScope, H3TurboLoraResult, H3TurboLoraTensorRef, H3TurboLoraTier,
};

fn failure(code: H3TurboLoraErrorCode, message: impl Into<String>) -> H3TurboLoraError {
    H3TurboLoraError {
        code,
        message: message.into(),
    }
}

/// One module's low-rank Turbo delta, applied as a parallel branch in the
/// original (unrotated) basis. It is never merged into an INT8 ConvRot weight.
///
/// The transposes are materialized once at construction: `down_t` is `Aᵀ` at
/// `[in, rank]` and `up_t` is `Bᵀ` at `[rank, out]`, so a forward is two
/// contiguous matmuls and one affine with no per-call transpose.
#[derive(Clone, Debug)]
pub struct H3TurboLoraDelta {
    down_t: Tensor,
    up_t: Tensor,
    scale: f64,
    rank: usize,
    in_features: usize,
    out_features: usize,
    device_bytes: u64,
}

impl H3TurboLoraDelta {
    /// Build from `A` at `[rank, in]` and `B` at `[out, rank]`, exactly the
    /// published `lora_A` / `lora_B` orientation.
    pub fn new(down: &Tensor, up: &Tensor, scale: f32) -> H3TurboLoraResult<Self> {
        let (rank, in_features) = down.dims2().map_err(|error| {
            failure(
                H3TurboLoraErrorCode::ShapeMismatch,
                format!("H3 Turbo lora_A must be rank 2: {error}"),
            )
        })?;
        let (out_features, up_rank) = up.dims2().map_err(|error| {
            failure(
                H3TurboLoraErrorCode::ShapeMismatch,
                format!("H3 Turbo lora_B must be rank 2: {error}"),
            )
        })?;
        if rank != up_rank {
            return Err(failure(
                H3TurboLoraErrorCode::ShapeMismatch,
                format!("H3 Turbo lora_A rank {rank} does not match lora_B rank {up_rank}"),
            ));
        }
        if rank == 0 || in_features == 0 || out_features == 0 {
            return Err(failure(
                H3TurboLoraErrorCode::ShapeMismatch,
                "H3 Turbo delta dimensions must all be positive",
            ));
        }
        if down.dtype() != up.dtype() {
            return Err(failure(
                H3TurboLoraErrorCode::DTypeMismatch,
                format!(
                    "H3 Turbo lora_A is {:?} but lora_B is {:?}",
                    down.dtype(),
                    up.dtype()
                ),
            ));
        }
        if !down.device().same_device(up.device()) {
            return Err(failure(
                H3TurboLoraErrorCode::ConfigMismatch,
                "H3 Turbo lora_A and lora_B must be resident on one device",
            ));
        }
        if !scale.is_finite() || scale <= 0.0 {
            return Err(failure(
                H3TurboLoraErrorCode::ScaleMismatch,
                format!("H3 Turbo delta scale {scale} must be finite and positive"),
            ));
        }
        let device_bytes = [down, up]
            .iter()
            .try_fold(0u64, |total, tensor| {
                tensor
                    .elem_count()
                    .checked_mul(tensor.dtype().size_in_bytes())
                    .and_then(|bytes| u64::try_from(bytes).ok())
                    .and_then(|bytes| total.checked_add(bytes))
            })
            .ok_or_else(|| {
                failure(
                    H3TurboLoraErrorCode::ConfigMismatch,
                    "H3 Turbo delta byte count overflows",
                )
            })?;
        let transpose = |tensor: &Tensor, label: &str| -> H3TurboLoraResult<Tensor> {
            tensor
                .t()
                .and_then(|value| value.contiguous())
                .map_err(|error| {
                    failure(
                        H3TurboLoraErrorCode::ConfigMismatch,
                        format!("H3 Turbo {label} could not be transposed: {error}"),
                    )
                })
        };
        Ok(Self {
            down_t: transpose(down, "lora_A")?,
            up_t: transpose(up, "lora_B")?,
            scale: f64::from(scale),
            rank,
            in_features,
            out_features,
            device_bytes,
        })
    }

    pub const fn rank(&self) -> usize {
        self.rank
    }

    pub const fn in_features(&self) -> usize {
        self.in_features
    }

    pub const fn out_features(&self) -> usize {
        self.out_features
    }

    pub const fn scale(&self) -> f64 {
        self.scale
    }

    /// Resident bytes of this delta's two matrices.
    pub const fn device_bytes(&self) -> u64 {
        self.device_bytes
    }

    pub fn dtype(&self) -> DType {
        self.down_t.dtype()
    }

    pub fn device(&self) -> &Device {
        self.down_t.device()
    }

    /// `((x @ Aᵀ) @ Bᵀ) · scale`, in `x`'s dtype and with `x`'s leading dims.
    pub fn delta(&self, x: &Tensor) -> candle::Result<Tensor> {
        let dims = x.dims();
        let last = *dims.last().ok_or_else(|| {
            candle::Error::Msg("MiniMax H3 Turbo delta input must have a last dimension".into())
        })?;
        if last != self.in_features {
            candle::bail!(
                "MiniMax H3 Turbo delta expects {} input features, got {last}",
                self.in_features
            )
        }
        let rows = dims[..dims.len() - 1].iter().product::<usize>();
        let flat = x.reshape((rows, self.in_features))?.contiguous()?;
        let (down_t, up_t) = if self.down_t.dtype() == flat.dtype() {
            (self.down_t.clone(), self.up_t.clone())
        } else {
            (
                self.down_t.to_dtype(flat.dtype())?,
                self.up_t.to_dtype(flat.dtype())?,
            )
        };
        let projected = flat.matmul(&down_t)?;
        let delta = projected.matmul(&up_t)?.affine(self.scale, 0.0)?;
        let mut shape = dims[..dims.len() - 1].to_vec();
        shape.push(self.out_features);
        delta.reshape(shape)
    }

    /// `base + delta(x)`. `base` must already be this module's base output.
    pub fn apply(&self, x: &Tensor, base: &Tensor) -> candle::Result<Tensor> {
        base.add(&self.delta(x)?)
    }
}

/// Optionally apply a delta to a base output; `None` is the identity, which is
/// what keeps an unadapted forward bit-identical.
pub(super) fn apply_optional_turbo_delta(
    delta: Option<&H3TurboLoraDelta>,
    input: &Tensor,
    base: Tensor,
) -> candle::Result<Tensor> {
    match delta {
        None => Ok(base),
        Some(delta) => delta.apply(input, &base),
    }
}

/// The four deltas overlaying one block's linears.
#[derive(Clone, Debug)]
pub struct H3TurboBlockDeltas {
    pub qkv: H3TurboLoraDelta,
    pub out: H3TurboLoraDelta,
    pub fc1: H3TurboLoraDelta,
    pub fc2: H3TurboLoraDelta,
}

impl H3TurboBlockDeltas {
    pub fn device_bytes(&self) -> u64 {
        self.qkv.device_bytes
            + self.out.device_bytes
            + self.fc1.device_bytes
            + self.fc2.device_bytes
    }

    /// The delta overlaying one of the four adapted linears.
    pub fn kind(&self, kind: H3TurboLoraModuleKind) -> &H3TurboLoraDelta {
        match kind {
            H3TurboLoraModuleKind::AttnQkvProj => &self.qkv,
            H3TurboLoraModuleKind::AttnOutProj => &self.out,
            H3TurboLoraModuleKind::MlpFc1 => &self.fc1,
            H3TurboLoraModuleKind::MlpFc2 => &self.fc2,
        }
    }
}

/// Refuse a Turbo overlay whose geometry or residency does not match the block
/// it is about to be attached to.
///
/// This runs at construction rather than at forward time so a mismatched
/// adapter fails before any denoise step is paid for.
pub(super) fn validate_turbo_block_shapes(
    deltas: &H3TurboBlockDeltas,
    hidden_size: usize,
    inner_dim: usize,
    ffn_hidden_size: usize,
    device: &Device,
) -> candle::Result<()> {
    let expected = [
        ("attn.qkv_proj", &deltas.qkv, hidden_size, 3 * inner_dim),
        ("attn.out_proj", &deltas.out, inner_dim, hidden_size),
        ("mlp.fc1", &deltas.fc1, hidden_size, 2 * ffn_hidden_size),
        ("mlp.fc2", &deltas.fc2, ffn_hidden_size, hidden_size),
    ];
    for (label, delta, in_features, out_features) in expected {
        if delta.in_features() != in_features || delta.out_features() != out_features {
            candle::bail!(
                "MiniMax H3 Turbo delta {label} is [{} -> {}], this block needs [{in_features} -> {out_features}]",
                delta.in_features(),
                delta.out_features()
            )
        }
        if !delta.device().same_device(device) {
            candle::bail!(
                "MiniMax H3 Turbo delta {label} is not resident on the block's execution device"
            )
        }
    }
    Ok(())
}

#[derive(Debug)]
enum H3TurboMainBlocks {
    Resident(Vec<H3TurboBlockDeltas>),
    MetalStreamed(H3TurboMainBlockStream),
}

struct H3TurboMainBlockStream {
    modules: Vec<[H3TurboLoraModule; 4]>,
    data_start: u64,
    device: Device,
    dtype: DType,
    cancellation: Arc<dyn H3ComfyInt8Cancellation>,
    identity: H3OpenedFileIdentity,
    state: Mutex<H3TurboMainBlockStreamState>,
}

#[derive(Debug)]
struct H3TurboMainBlockStreamState {
    file: File,
}

impl std::fmt::Debug for H3TurboMainBlockStream {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter
            .debug_struct("H3TurboMainBlockStream")
            .field("modules", &self.modules.len())
            .field("data_start", &self.data_start)
            .field("device", &self.device)
            .field("dtype", &self.dtype)
            .field("identity", &self.identity)
            .finish_non_exhaustive()
    }
}

/// Authenticated Turbo deltas. CUDA keeps every block resident; Metal keeps
/// token refiners resident and streams exactly one main-block slice at a time.
#[derive(Debug)]
pub struct H3TurboLoraRuntime {
    tier: H3TurboLoraTier,
    adapter_identity_sha256: String,
    content_sha256: String,
    scale: f32,
    main_blocks: H3TurboMainBlocks,
    token_refiner_blocks: Vec<H3TurboBlockDeltas>,
    device_bytes: u64,
    device_staging_peak_bytes: u64,
    host_staging_peak_bytes: u64,
    streamed_main_block_device_bytes: u64,
}

impl H3TurboLoraRuntime {
    pub fn tier(&self) -> H3TurboLoraTier {
        self.tier
    }

    /// The authenticated adapter identity, for a frozen execution plan that
    /// has to record which weights actually ran.
    pub fn adapter_identity_sha256(&self) -> &str {
        &self.adapter_identity_sha256
    }

    pub fn content_sha256(&self) -> &str {
        &self.content_sha256
    }

    /// The one `alpha / rank` every module agreed on.
    pub const fn scale(&self) -> f32 {
        self.scale
    }

    pub fn block_count(&self) -> usize {
        match &self.main_blocks {
            H3TurboMainBlocks::Resident(blocks) => blocks.len(),
            H3TurboMainBlocks::MetalStreamed(stream) => stream.modules.len(),
        }
    }

    pub fn token_refiner_block_count(&self) -> usize {
        self.token_refiner_blocks.len()
    }

    pub fn main_block(&self, index: usize) -> Option<&H3TurboBlockDeltas> {
        match &self.main_blocks {
            H3TurboMainBlocks::Resident(blocks) => blocks.get(index),
            H3TurboMainBlocks::MetalStreamed(_) => None,
        }
    }

    /// Resolve one main-block slice. CUDA clones resident tensor handles;
    /// Metal reads the exact authenticated block from its retained descriptor.
    pub fn load_main_block(&self, index: usize) -> H3TurboLoraResult<H3TurboBlockDeltas> {
        match &self.main_blocks {
            H3TurboMainBlocks::Resident(blocks) => blocks.get(index).cloned().ok_or_else(|| {
                failure(
                    H3TurboLoraErrorCode::MissingModule,
                    format!("MiniMax H3 Turbo adapter has no main block {index}"),
                )
            }),
            H3TurboMainBlocks::MetalStreamed(stream) => stream.load_block(index),
        }
    }

    pub fn token_refiner_block(&self, index: usize) -> Option<&H3TurboBlockDeltas> {
        self.token_refiner_blocks.get(index)
    }

    /// Exact resident device bytes of every `lora_A` / `lora_B` matrix.
    ///
    /// The 208 `alpha` scalars are folded into each delta's `scale` at load
    /// and never stay resident, so this is the adapter's payload minus
    /// `208 * 4` bytes.
    pub const fn device_bytes(&self) -> u64 {
        self.device_bytes
    }

    /// Transient *device* bytes the load peaks at above the residents.
    ///
    /// [`H3TurboLoraDelta::new`] materializes `A^T` and `B^T` while the freshly
    /// uploaded `A` and `B` are still alive, so during module `i` the device
    /// holds every finished module plus `2*b_i`, where `b_i = |A_i| + |B_i|`:
    ///
    /// ```text
    /// peak = max_i [ sum_{j<i} b_j + 2*b_i ] = max_i [ sum_{j<=i} b_j + b_i ]
    ///      <= (sum_j b_j) + max_i b_i = device_bytes + device_staging_peak_bytes
    /// ```
    ///
    /// so charging this on top of [`Self::device_bytes`] is a sound upper
    /// bound. For the published tiers the widest module is the fused
    /// `attn.qkv_proj` at 20,643,840 bytes. The transposes are released before
    /// the denoise begins, which is why only the transformer-load phase pays
    /// it.
    pub const fn device_staging_peak_bytes(&self) -> u64 {
        self.device_staging_peak_bytes
    }

    /// Transient host bytes the load peaks at.
    ///
    /// Tensors are read one at a time into a `Vec<u8>` and then materialized as
    /// a CPU tensor before the device copy, so the peak is twice the largest
    /// single `lora_A` / `lora_B` matrix — 33,030,144 bytes for the published
    /// tiers, whose widest matrix is the fused `lora_B` at `[21504, 384]`.
    /// Nothing else is staged, and the buffer is released per tensor.
    pub const fn host_staging_peak_bytes(&self) -> u64 {
        self.host_staging_peak_bytes
    }

    /// One streamed Metal main-block slice. Zero on the resident CUDA route.
    pub const fn streamed_main_block_device_bytes(&self) -> u64 {
        self.streamed_main_block_device_bytes
    }

    pub const fn is_metal_streamed(&self) -> bool {
        matches!(&self.main_blocks, H3TurboMainBlocks::MetalStreamed(_))
    }

    /// Build from an authenticated contract plus the descriptor the digest was
    /// computed over.
    pub fn from_authenticated(
        contract: &H3TurboLoraContract,
        file: &mut File,
        device: &Device,
        dtype: DType,
        cancellation: &dyn H3ComfyInt8Cancellation,
    ) -> H3TurboLoraResult<Self> {
        if !matches!(dtype, DType::BF16 | DType::F16 | DType::F32 | DType::F64) {
            return Err(failure(
                H3TurboLoraErrorCode::DTypeMismatch,
                format!("H3 Turbo runtime requires a floating compute dtype, got {dtype:?}"),
            ));
        }
        let inspection = contract.inspection();
        let data_start = 8u64.checked_add(inspection.header_len).ok_or_else(|| {
            failure(
                H3TurboLoraErrorCode::InvalidHeader,
                "H3 Turbo adapter data offset overflows",
            )
        })?;

        let mut main = BTreeMap::<usize, BTreeMap<H3TurboLoraModuleKind, H3TurboLoraDelta>>::new();
        let mut refiner =
            BTreeMap::<usize, BTreeMap<H3TurboLoraModuleKind, H3TurboLoraDelta>>::new();
        let mut device_bytes = 0u64;
        let mut widest_matrix_bytes = 0u64;
        let mut widest_module_bytes = 0u64;
        for module in inspection.modules.values() {
            cancellation_boundary(cancellation)?;
            let mut module_bytes = 0u64;
            for reference in [&module.lora_a, &module.lora_b] {
                let bytes = reference.data_offsets[1] - reference.data_offsets[0];
                widest_matrix_bytes = widest_matrix_bytes.max(bytes);
                module_bytes = module_bytes.checked_add(bytes).ok_or_else(|| {
                    failure(
                        H3TurboLoraErrorCode::ConfigMismatch,
                        "H3 Turbo module byte count overflows",
                    )
                })?;
            }
            widest_module_bytes = widest_module_bytes.max(module_bytes);
            let delta = load_module_delta(module, file, data_start, device, dtype, cancellation)?;
            device_bytes = device_bytes
                .checked_add(delta.device_bytes())
                .ok_or_else(|| {
                    failure(
                        H3TurboLoraErrorCode::ConfigMismatch,
                        "H3 Turbo resident byte count overflows",
                    )
                })?;
            let target = match module.scope {
                H3TurboLoraModuleScope::MainBlock(index) => main.entry(index).or_default(),
                H3TurboLoraModuleScope::TokenRefinerBlock(index) => {
                    refiner.entry(index).or_default()
                }
            };
            if target.insert(module.kind, delta).is_some() {
                return Err(failure(
                    H3TurboLoraErrorCode::ConfigMismatch,
                    format!("H3 Turbo module {:?} was resolved twice", module.name),
                ));
            }
        }

        Ok(Self {
            tier: contract.tier(),
            adapter_identity_sha256: contract.adapter_identity_sha256().to_owned(),
            content_sha256: contract.content_sha256().to_owned(),
            scale: inspection.scale,
            main_blocks: H3TurboMainBlocks::Resident(collect_contiguous_blocks(main, "main")?),
            token_refiner_blocks: collect_contiguous_blocks(refiner, "token refiner")?,
            device_bytes,
            device_staging_peak_bytes: widest_module_bytes,
            host_staging_peak_bytes: widest_matrix_bytes.checked_mul(2).ok_or_else(|| {
                failure(
                    H3TurboLoraErrorCode::ConfigMismatch,
                    "H3 Turbo host staging byte count overflows",
                )
            })?,
            streamed_main_block_device_bytes: 0,
        })
    }

    /// Metal-only constructor retaining the authenticated descriptor and only
    /// the two token-refiner adapter blocks on the execution device.
    pub fn open_metal_streamed(
        path: &Path,
        tier: H3TurboLoraTier,
        device: &Device,
        dtype: DType,
        cancellation: Arc<dyn H3ComfyInt8Cancellation>,
    ) -> H3TurboLoraResult<Self> {
        Self::open_metal_streamed_against(
            path,
            &tier.expectation(),
            tier,
            device,
            dtype,
            cancellation,
        )
    }

    fn open_metal_streamed_against(
        path: &Path,
        expectation: &H3TurboLoraExpectation,
        tier: H3TurboLoraTier,
        device: &Device,
        dtype: DType,
        cancellation: Arc<dyn H3ComfyInt8Cancellation>,
    ) -> H3TurboLoraResult<Self> {
        if !device.is_metal() {
            return Err(failure(
                H3TurboLoraErrorCode::ConfigMismatch,
                "MiniMax H3 streamed Turbo adapters are Metal-only",
            ));
        }
        let (contract, mut file) = authenticate_h3_turbo_lora_adapter_retaining(
            path,
            expectation,
            tier,
            cancellation.as_ref(),
        )?;
        disable_file_cache_on_macos(&file)?;
        let identity = H3OpenedFileIdentity::from_metadata(
            &file
                .metadata()
                .map_err(|error| failure(H3TurboLoraErrorCode::Io, error.to_string()))?,
        );
        let inspection = contract.inspection();
        let data_start = 8u64.checked_add(inspection.header_len).ok_or_else(|| {
            failure(
                H3TurboLoraErrorCode::InvalidHeader,
                "H3 Turbo adapter data offset overflows",
            )
        })?;
        let mut refiner = BTreeMap::new();
        let mut token_refiner_device_bytes = 0u64;
        for module in inspection
            .modules
            .values()
            .filter(|module| matches!(module.scope, H3TurboLoraModuleScope::TokenRefinerBlock(_)))
        {
            cancellation_boundary(cancellation.as_ref())?;
            let delta = load_module_delta(
                module,
                &mut file,
                data_start,
                device,
                dtype,
                cancellation.as_ref(),
            )?;
            token_refiner_device_bytes = token_refiner_device_bytes
                .checked_add(delta.device_bytes())
                .ok_or_else(|| {
                    failure(
                        H3TurboLoraErrorCode::ConfigMismatch,
                        "H3 Turbo token-refiner byte count overflows",
                    )
                })?;
            let H3TurboLoraModuleScope::TokenRefinerBlock(index) = module.scope else {
                unreachable!("filter retains token-refiner modules only")
            };
            if refiner
                .entry(index)
                .or_insert_with(BTreeMap::new)
                .insert(module.kind, delta)
                .is_some()
            {
                return Err(failure(
                    H3TurboLoraErrorCode::ConfigMismatch,
                    format!("H3 Turbo module {:?} was resolved twice", module.name),
                ));
            }
        }
        let modules = collect_streamed_main_modules(inspection)?;
        let mut streamed_main_block_device_bytes = 0u64;
        for block in &modules {
            let block_bytes = block.iter().try_fold(0u64, |total, module| {
                total
                    .checked_add(module_delta_device_bytes(module, dtype)?)
                    .ok_or_else(|| {
                        failure(
                            H3TurboLoraErrorCode::ConfigMismatch,
                            "H3 Turbo streamed block byte count overflows",
                        )
                    })
            })?;
            streamed_main_block_device_bytes = streamed_main_block_device_bytes.max(block_bytes);
        }
        let widest_matrix_bytes = inspection
            .modules
            .values()
            .flat_map(|module| [&module.lora_a, &module.lora_b])
            .map(tensor_ref_bytes)
            .max()
            .unwrap_or(0);
        let widest_module_bytes = inspection
            .modules
            .values()
            .map(module_delta_bytes)
            .max()
            .unwrap_or(0);
        verify_opened_file_identity(&file, &identity)?;
        Ok(Self {
            tier: contract.tier(),
            adapter_identity_sha256: contract.adapter_identity_sha256().to_owned(),
            content_sha256: contract.content_sha256().to_owned(),
            scale: inspection.scale,
            main_blocks: H3TurboMainBlocks::MetalStreamed(H3TurboMainBlockStream {
                modules,
                data_start,
                device: device.clone(),
                dtype,
                cancellation,
                identity,
                state: Mutex::new(H3TurboMainBlockStreamState { file }),
            }),
            token_refiner_blocks: collect_contiguous_blocks(refiner, "token refiner")?,
            device_bytes: token_refiner_device_bytes,
            device_staging_peak_bytes: widest_module_bytes,
            host_staging_peak_bytes: widest_matrix_bytes.checked_mul(2).ok_or_else(|| {
                failure(
                    H3TurboLoraErrorCode::ConfigMismatch,
                    "H3 Turbo host staging byte count overflows",
                )
            })?,
            streamed_main_block_device_bytes,
        })
    }

    /// Authenticate one published adapter and load every delta onto `device`.
    ///
    /// The tensors are read through the exact descriptor whose complete
    /// content digest was just verified, so the resident deltas are provably
    /// the reviewed bytes.
    pub fn open(
        path: &Path,
        tier: H3TurboLoraTier,
        device: &Device,
        dtype: DType,
        cancellation: &dyn H3ComfyInt8Cancellation,
    ) -> H3TurboLoraResult<Self> {
        Self::open_against(path, &tier.expectation(), tier, device, dtype, cancellation)
    }

    pub(crate) fn open_against(
        path: &Path,
        expectation: &H3TurboLoraExpectation,
        tier: H3TurboLoraTier,
        device: &Device,
        dtype: DType,
        cancellation: &dyn H3ComfyInt8Cancellation,
    ) -> H3TurboLoraResult<Self> {
        let (contract, mut file) =
            authenticate_h3_turbo_lora_adapter_retaining(path, expectation, tier, cancellation)?;
        Self::from_authenticated(&contract, &mut file, device, dtype, cancellation)
    }
}

impl H3TurboMainBlockStream {
    fn load_block(&self, index: usize) -> H3TurboLoraResult<H3TurboBlockDeltas> {
        cancellation_boundary(self.cancellation.as_ref())?;
        let modules = self.modules.get(index).ok_or_else(|| {
            failure(
                H3TurboLoraErrorCode::MissingModule,
                format!("MiniMax H3 Turbo adapter has no main block {index}"),
            )
        })?;
        let mut state = self.state.lock().map_err(|_| {
            failure(
                H3TurboLoraErrorCode::Io,
                "H3 Turbo stream lock was poisoned",
            )
        })?;
        verify_opened_file_identity(&state.file, &self.identity)?;
        let mut deltas = BTreeMap::new();
        for module in modules {
            cancellation_boundary(self.cancellation.as_ref())?;
            let delta = load_module_delta(
                module,
                &mut state.file,
                self.data_start,
                &self.device,
                self.dtype,
                self.cancellation.as_ref(),
            )?;
            if deltas.insert(module.kind, delta).is_some() {
                return Err(failure(
                    H3TurboLoraErrorCode::ConfigMismatch,
                    format!("H3 Turbo module {:?} was resolved twice", module.name),
                ));
            }
        }
        verify_opened_file_identity(&state.file, &self.identity)?;
        collect_one_block_deltas(index, deltas, "streamed main")
    }
}

fn collect_streamed_main_modules(
    inspection: &super::turbo_lora::H3TurboLoraInspection,
) -> H3TurboLoraResult<Vec<[H3TurboLoraModule; 4]>> {
    let mut blocks = BTreeMap::<usize, BTreeMap<H3TurboLoraModuleKind, H3TurboLoraModule>>::new();
    for module in inspection
        .modules
        .values()
        .filter(|module| matches!(module.scope, H3TurboLoraModuleScope::MainBlock(_)))
    {
        let H3TurboLoraModuleScope::MainBlock(index) = module.scope else {
            unreachable!("filter retains main-block modules only")
        };
        if blocks
            .entry(index)
            .or_default()
            .insert(module.kind, module.clone())
            .is_some()
        {
            return Err(failure(
                H3TurboLoraErrorCode::ConfigMismatch,
                format!("H3 Turbo module {:?} was indexed twice", module.name),
            ));
        }
    }
    let mut resolved = Vec::with_capacity(blocks.len());
    for (expected, (index, mut modules)) in blocks.into_iter().enumerate() {
        if index != expected {
            return Err(failure(
                H3TurboLoraErrorCode::MissingModule,
                "H3 Turbo streamed main-block indices are not contiguous from zero",
            ));
        }
        let mut take = |kind| {
            modules.remove(&kind).ok_or_else(|| {
                failure(
                    H3TurboLoraErrorCode::MissingModule,
                    format!("H3 Turbo streamed main block {index} is missing {kind:?}"),
                )
            })
        };
        resolved.push([
            take(H3TurboLoraModuleKind::AttnQkvProj)?,
            take(H3TurboLoraModuleKind::AttnOutProj)?,
            take(H3TurboLoraModuleKind::MlpFc1)?,
            take(H3TurboLoraModuleKind::MlpFc2)?,
        ]);
    }
    Ok(resolved)
}

fn tensor_ref_bytes(reference: &H3TurboLoraTensorRef) -> u64 {
    reference.data_offsets[1] - reference.data_offsets[0]
}

fn module_delta_bytes(module: &H3TurboLoraModule) -> u64 {
    tensor_ref_bytes(&module.lora_a) + tensor_ref_bytes(&module.lora_b)
}

fn module_delta_device_bytes(module: &H3TurboLoraModule, dtype: DType) -> H3TurboLoraResult<u64> {
    module_delta_bytes(module)
        .checked_div(2)
        .and_then(|elements| elements.checked_mul(dtype.size_in_bytes() as u64))
        .ok_or_else(|| {
            failure(
                H3TurboLoraErrorCode::ConfigMismatch,
                "H3 Turbo streamed module byte count overflows",
            )
        })
}

fn verify_opened_file_identity(
    file: &File,
    expected: &H3OpenedFileIdentity,
) -> H3TurboLoraResult<()> {
    let actual = H3OpenedFileIdentity::from_metadata(
        &file
            .metadata()
            .map_err(|error| failure(H3TurboLoraErrorCode::Io, error.to_string()))?,
    );
    if &actual != expected {
        return Err(failure(
            H3TurboLoraErrorCode::FileIdentityChanged,
            "opened H3 Turbo adapter changed during streamed execution",
        ));
    }
    Ok(())
}

#[cfg(target_os = "macos")]
fn disable_file_cache_on_macos(file: &File) -> H3TurboLoraResult<()> {
    use std::os::fd::AsRawFd;
    // SAFETY: F_NOCACHE reads the descriptor and integer enable flag only.
    let result = unsafe { libc::fcntl(file.as_raw_fd(), libc::F_NOCACHE, 1) };
    if result == -1 {
        return Err(failure(
            H3TurboLoraErrorCode::Io,
            format!(
                "failed to disable caching for streamed H3 Turbo adapter: {}",
                std::io::Error::last_os_error()
            ),
        ));
    }
    Ok(())
}

#[cfg(not(target_os = "macos"))]
fn disable_file_cache_on_macos(_file: &File) -> H3TurboLoraResult<()> {
    Ok(())
}

fn cancellation_boundary(cancellation: &dyn H3ComfyInt8Cancellation) -> H3TurboLoraResult<()> {
    if cancellation.is_cancelled() {
        return Err(failure(
            H3TurboLoraErrorCode::Cancelled,
            "MiniMax H3 Turbo adapter load was cancelled",
        ));
    }
    Ok(())
}

fn collect_contiguous_blocks(
    blocks: BTreeMap<usize, BTreeMap<H3TurboLoraModuleKind, H3TurboLoraDelta>>,
    label: &str,
) -> H3TurboLoraResult<Vec<H3TurboBlockDeltas>> {
    let mut resolved = Vec::with_capacity(blocks.len());
    for (expected_index, (index, kinds)) in blocks.into_iter().enumerate() {
        if index != expected_index {
            return Err(failure(
                H3TurboLoraErrorCode::MissingModule,
                format!("H3 Turbo {label} block indices are not contiguous from zero"),
            ));
        }
        resolved.push(collect_one_block_deltas(index, kinds, label)?);
    }
    Ok(resolved)
}

fn collect_one_block_deltas(
    index: usize,
    mut kinds: BTreeMap<H3TurboLoraModuleKind, H3TurboLoraDelta>,
    label: &str,
) -> H3TurboLoraResult<H3TurboBlockDeltas> {
    let mut take = |kind: H3TurboLoraModuleKind| -> H3TurboLoraResult<H3TurboLoraDelta> {
        kinds.remove(&kind).ok_or_else(|| {
            failure(
                H3TurboLoraErrorCode::MissingModule,
                format!("H3 Turbo {label} block {index} is missing {kind:?}"),
            )
        })
    };
    Ok(H3TurboBlockDeltas {
        qkv: take(H3TurboLoraModuleKind::AttnQkvProj)?,
        out: take(H3TurboLoraModuleKind::AttnOutProj)?,
        fc1: take(H3TurboLoraModuleKind::MlpFc1)?,
        fc2: take(H3TurboLoraModuleKind::MlpFc2)?,
    })
}

fn load_module_delta(
    module: &H3TurboLoraModule,
    file: &mut File,
    data_start: u64,
    device: &Device,
    dtype: DType,
    cancellation: &dyn H3ComfyInt8Cancellation,
) -> H3TurboLoraResult<H3TurboLoraDelta> {
    let down = read_delta_tensor(
        &module.lora_a,
        file,
        data_start,
        device,
        dtype,
        cancellation,
    )?;
    let up = read_delta_tensor(
        &module.lora_b,
        file,
        data_start,
        device,
        dtype,
        cancellation,
    )?;
    let delta = H3TurboLoraDelta::new(&down, &up, module.scale)?;
    // Each constructor transposes both source matrices into the retained
    // layout. Metal queues those copies asynchronously and otherwise keeps
    // every module's read/conversion/transpose sources alive until the entire
    // 208-module adapter finishes loading. Fence at the declared one-module
    // staging boundary so peak memory matches admission. CUDA and CPU retain
    // their existing asynchronous path.
    if turbo_load_requires_synchronization(device.location()) {
        // The retained delta owns contiguous transposes; the source uploads
        // are no longer part of the model. Release their last handles before
        // the Metal fence so `drop_unused_buffers` can actually return those
        // allocations instead of observing them as live and carrying them
        // into the next module.
        drop(down);
        drop(up);
        device.synchronize().map_err(|error| {
            failure(
                H3TurboLoraErrorCode::Io,
                format!(
                    "failed to synchronize H3 Turbo module {:?}: {error}",
                    module.name
                ),
            )
        })?;
    }
    if delta.rank() != module.rank
        || delta.in_features() != module.in_features
        || delta.out_features() != module.out_features
    {
        return Err(failure(
            H3TurboLoraErrorCode::ShapeMismatch,
            format!(
                "H3 Turbo module {:?} loaded as rank {} [{} -> {}], contract says rank {} [{} -> {}]",
                module.name,
                delta.rank(),
                delta.in_features(),
                delta.out_features(),
                module.rank,
                module.in_features,
                module.out_features
            ),
        ));
    }
    Ok(delta)
}

fn turbo_load_requires_synchronization(location: DeviceLocation) -> bool {
    matches!(location, DeviceLocation::Metal { .. })
}

fn read_delta_tensor(
    reference: &H3TurboLoraTensorRef,
    file: &mut File,
    data_start: u64,
    device: &Device,
    dtype: DType,
    cancellation: &dyn H3ComfyInt8Cancellation,
) -> H3TurboLoraResult<Tensor> {
    if reference.dtype != "BF16" {
        return Err(failure(
            H3TurboLoraErrorCode::DTypeMismatch,
            format!(
                "H3 Turbo tensor {:?} must be BF16 storage, found {}",
                reference.name, reference.dtype
            ),
        ));
    }
    let len =
        usize::try_from(reference.data_offsets[1] - reference.data_offsets[0]).map_err(|_| {
            failure(
                H3TurboLoraErrorCode::InvalidHeader,
                format!("H3 Turbo tensor {:?} is too large", reference.name),
            )
        })?;
    let start = data_start
        .checked_add(reference.data_offsets[0])
        .ok_or_else(|| {
            failure(
                H3TurboLoraErrorCode::InvalidHeader,
                format!("H3 Turbo tensor {:?} offset overflows", reference.name),
            )
        })?;
    file.seek(SeekFrom::Start(start)).map_err(|error| {
        failure(
            H3TurboLoraErrorCode::Io,
            format!(
                "failed to seek H3 Turbo tensor {:?}: {error}",
                reference.name
            ),
        )
    })?;
    let mut bytes = vec![0u8; len];
    let mut offset = 0usize;
    while offset < bytes.len() {
        cancellation_boundary(cancellation)?;
        let end = (offset + FILE_READ_CHUNK_BYTES).min(bytes.len());
        file.read_exact(&mut bytes[offset..end]).map_err(|error| {
            failure(
                H3TurboLoraErrorCode::Io,
                format!(
                    "failed to read H3 Turbo tensor {:?}: {error}",
                    reference.name
                ),
            )
        })?;
        offset = end;
    }
    let tensor = Tensor::from_raw_buffer(&bytes, DType::BF16, &reference.shape, &Device::Cpu)
        .and_then(|tensor| {
            if dtype == DType::BF16 {
                Ok(tensor)
            } else {
                tensor.to_dtype(dtype)
            }
        })
        .and_then(|tensor| tensor.to_device(device))
        .map_err(|error| {
            failure(
                H3TurboLoraErrorCode::Io,
                format!(
                    "failed to materialize H3 Turbo tensor {:?}: {error}",
                    reference.name
                ),
            )
        })?;
    Ok(tensor)
}

#[cfg(test)]
mod tests {
    use super::super::comfy_dit::H3ComfyNeverCancel;
    use super::super::turbo_lora::fixtures;
    use super::*;

    #[test]
    fn turbo_load_fences_only_metal_uploads() {
        assert!(turbo_load_requires_synchronization(DeviceLocation::Metal {
            gpu_id: 0
        }));
        assert!(!turbo_load_requires_synchronization(DeviceLocation::Cpu));
        assert!(!turbo_load_requires_synchronization(DeviceLocation::Cuda {
            gpu_id: 0
        }));
    }

    #[test]
    fn a_delta_computes_the_low_rank_product_with_its_scale() {
        let device = Device::Cpu;
        let down = Tensor::new(&[[1.0f32, 0.0, 2.0], [0.0, 3.0, -1.0]], &device).unwrap();
        let up = Tensor::new(
            &[[1.0f32, 2.0], [-1.0, 0.5], [0.0, 1.0], [4.0, 0.0]],
            &device,
        )
        .unwrap();
        let delta = H3TurboLoraDelta::new(&down, &up, 0.25).unwrap();
        assert_eq!(delta.rank(), 2);
        assert_eq!(delta.in_features(), 3);
        assert_eq!(delta.out_features(), 4);

        let x = Tensor::new(&[[1.0f32, 2.0, 3.0], [-1.0, 0.0, 0.5]], &device).unwrap();
        let observed = delta.delta(&x).unwrap().to_vec2::<f32>().unwrap();

        // Reference: x @ (scale * (B @ A))^T
        let merged = up.matmul(&down).unwrap().affine(0.25, 0.0).unwrap();
        let expected = x
            .matmul(&merged.t().unwrap().contiguous().unwrap())
            .unwrap()
            .to_vec2::<f32>()
            .unwrap();
        for (row, expected_row) in observed.iter().zip(expected.iter()) {
            for (value, expected_value) in row.iter().zip(expected_row.iter()) {
                assert!(
                    (value - expected_value).abs() < 1e-5,
                    "{value} {expected_value}"
                );
            }
        }
    }

    #[test]
    fn a_delta_rejects_inconsistent_shapes_dtypes_and_scales() {
        let device = Device::Cpu;
        let down = Tensor::zeros((2, 3), DType::F32, &device).unwrap();
        let up = Tensor::zeros((4, 3), DType::F32, &device).unwrap();
        assert_eq!(
            H3TurboLoraDelta::new(&down, &up, 1.0).unwrap_err().code,
            H3TurboLoraErrorCode::ShapeMismatch
        );

        let up = Tensor::zeros((4, 2), DType::F32, &device).unwrap();
        for scale in [0.0f32, -1.0, f32::NAN] {
            assert_eq!(
                H3TurboLoraDelta::new(&down, &up, scale).unwrap_err().code,
                H3TurboLoraErrorCode::ScaleMismatch
            );
        }

        let wide = Tensor::zeros((4, 2), DType::F64, &device).unwrap();
        assert_eq!(
            H3TurboLoraDelta::new(&down, &wide, 1.0).unwrap_err().code,
            H3TurboLoraErrorCode::DTypeMismatch
        );
    }

    /// A rank-`r` delta built from explicit matrices, for the fused-QKV proof.
    fn delta_of(down: &Tensor, up: &Tensor, scale: f32) -> H3TurboLoraDelta {
        H3TurboLoraDelta::new(down, up, scale).unwrap()
    }

    fn ramp(rows: usize, cols: usize, seed: usize, device: &Device) -> Tensor {
        let values = (0..rows * cols)
            .map(|index| ((index.wrapping_mul(37).wrapping_add(seed)) % 23) as f32 / 11.0 - 1.0)
            .collect::<Vec<_>>();
        Tensor::from_vec(values, (rows, cols), device).unwrap()
    }

    #[test]
    fn the_scale_is_alpha_over_rank_and_is_applied_linearly() {
        let device = Device::Cpu;
        let down = ramp(4, 6, 1, &device);
        let up = ramp(5, 4, 2, &device);
        let x = ramp(3, 6, 3, &device);

        // 8/128 and 24/384 are the published non-fused and fused alpha/rank
        // pairs; they must resolve to the identical scale.
        assert_eq!(8.0f32 / 128.0, 24.0f32 / 384.0);
        let unit = delta_of(&down, &up, 1.0).delta(&x).unwrap();
        for scale in [8.0f32 / 128.0, 128.0 / 128.0, 384.0 / 384.0, 0.5] {
            let scaled = delta_of(&down, &up, scale).delta(&x).unwrap();
            let expected = unit.affine(f64::from(scale), 0.0).unwrap();
            let observed = scaled.to_vec2::<f32>().unwrap();
            let expected = expected.to_vec2::<f32>().unwrap();
            for (row, expected_row) in observed.iter().zip(expected.iter()) {
                for (value, want) in row.iter().zip(expected_row.iter()) {
                    assert!((value - want).abs() < 1e-5, "{scale}: {value} vs {want}");
                }
            }
        }
    }

    #[test]
    fn fused_qkv_routing_equals_three_independent_deltas() {
        // `qkv_fusion` is "block diagonal B; concat A; alpha multiplied by 3".
        // Build that layout explicitly and prove the naive (x @ Aᵀ) @ Bᵀ
        // reproduces three independent rank-r deltas concatenated on the
        // output axis — which is why no FusedSlice bookkeeping is needed.
        //
        // The second case is the one an SVD-resized adapter actually ships:
        // the three projections are compressed INDEPENDENTLY, so `A` is a
        // concatenation of three different ranks and `B`'s diagonal blocks are
        // different widths. The structural zeros still do the routing, so the
        // fused delta stays exact with no per-projection bookkeeping — which
        // is what lets one rank number per module describe a resized file.
        let device = Device::Cpu;
        let in_features = 5usize;
        let out_each = 3usize;
        let alpha = 4.0f32;

        // Uniform: alpha multiplied by three keeps alpha/rank unchanged.
        assert_eq!((alpha * 3.0) / (2 * 3) as f32, alpha / 2.0);

        for (ranks, scale) in [
            // The published rank-128 layout, in miniature.
            ([2usize, 2, 2], alpha / 2.0),
            // A resized layout: unequal per-projection ranks, and a scale of
            // one because it is already inside `lora_B`.
            ([1usize, 5, 3], 1.0f32),
        ] {
            let a = [
                ramp(ranks[0], in_features, 11, &device),
                ramp(ranks[1], in_features, 12, &device),
                ramp(ranks[2], in_features, 13, &device),
            ];
            let b = [
                ramp(out_each, ranks[0], 21, &device),
                ramp(out_each, ranks[1], 22, &device),
                ramp(out_each, ranks[2], 23, &device),
            ];

            // concat A on the rank axis
            let fused_rank = ranks.iter().sum::<usize>();
            let fused_a = Tensor::cat(&[&a[0], &a[1], &a[2]], 0).unwrap();
            assert_eq!(fused_a.dims(), &[fused_rank, in_features]);

            // block-diagonal B: [3*out_each, sum(ranks)], with each block's own
            // width, so the zeros route each projection to its own output slab.
            let zero =
                |columns: usize| Tensor::zeros((out_each, columns), DType::F32, &device).unwrap();
            let rows = [
                Tensor::cat(&[&b[0], &zero(ranks[1]), &zero(ranks[2])], 1).unwrap(),
                Tensor::cat(&[&zero(ranks[0]), &b[1], &zero(ranks[2])], 1).unwrap(),
                Tensor::cat(&[&zero(ranks[0]), &zero(ranks[1]), &b[2]], 1).unwrap(),
            ];
            let fused_b = Tensor::cat(&[&rows[0], &rows[1], &rows[2]], 0).unwrap();
            assert_eq!(fused_b.dims(), &[3 * out_each, fused_rank]);

            let x = ramp(4, in_features, 31, &device);
            let fused_delta = delta_of(&fused_a, &fused_b, scale);
            assert_eq!(fused_delta.rank(), fused_rank);
            let fused = fused_delta.delta(&x).unwrap().to_vec2::<f32>().unwrap();

            let independent = (0..3)
                .map(|index| {
                    delta_of(&a[index], &b[index], scale)
                        .delta(&x)
                        .unwrap()
                        .to_vec2::<f32>()
                        .unwrap()
                })
                .collect::<Vec<_>>();

            for row in 0..4 {
                for part in 0..3 {
                    for column in 0..out_each {
                        let observed = fused[row][part * out_each + column];
                        let expected = independent[part][row][column];
                        assert!(
                            (observed - expected).abs() < 1e-5,
                            "{ranks:?} row {row} part {part} col {column}: {observed} vs {expected}"
                        );
                    }
                }
            }
        }
    }

    #[test]
    fn a_delta_reshapes_batched_activations() {
        let device = Device::Cpu;
        let down = ramp(2, 4, 5, &device);
        let up = ramp(3, 2, 6, &device);
        let delta = delta_of(&down, &up, 0.25);
        let x = Tensor::from_vec(
            (0..2 * 5 * 4)
                .map(|index| index as f32 / 13.0)
                .collect::<Vec<_>>(),
            (2, 5, 4),
            &device,
        )
        .unwrap();
        let out = delta.delta(&x).unwrap();
        assert_eq!(out.dims(), &[2, 5, 3]);

        // Row-for-row agreement with the flattened computation.
        let flat = delta.delta(&x.reshape((10, 4)).unwrap()).unwrap();
        let batched = out.reshape((10, 3)).unwrap().to_vec2::<f32>().unwrap();
        let reference = flat.to_vec2::<f32>().unwrap();
        assert_eq!(batched, reference);
    }

    #[test]
    fn a_delta_refuses_an_input_width_it_was_not_built_for() {
        let device = Device::Cpu;
        let delta = delta_of(&ramp(2, 4, 1, &device), &ramp(3, 2, 2, &device), 1.0);
        assert!(delta.delta(&ramp(2, 5, 3, &device)).is_err());
    }

    /// The exact resident cost of a published adapter, derived from the pinned
    /// module geometry rather than restated.
    #[test]
    fn resident_device_bytes_are_the_published_payload_minus_the_alpha_scalars() {
        let expectation = H3TurboLoraTier::Fl2v8StepV10.expectation();
        let (modules, _) = super::super::turbo_lora::expected_turbo_modules(&expectation)
            .expect("published geometry");
        let mut matrix_elements = 0u64;
        for module in modules.values() {
            let rank = module.rank.bound();
            matrix_elements += (rank * module.in_features) as u64;
            matrix_elements += (module.out_features * rank) as u64;
        }
        let matrix_bytes = matrix_elements * 2; // BF16

        // Payload = every lora_A/lora_B byte plus one F32 alpha per module.
        assert_eq!(
            matrix_bytes + (modules.len() as u64) * 4,
            super::super::turbo_lora::H3_TURBO_LORA_PAYLOAD_BYTES
        );
        // 1,956,118,528 bytes = 1.8216 GiB stay resident for the whole denoise.
        assert_eq!(matrix_bytes, 1_956_118_528);
    }

    /// Rebuild one adapter matrix from the fixture generator, without reading
    /// the file, so the loaded tensor can be checked independently.
    fn expected_matrix(name: &str, rows: usize, cols: usize) -> Tensor {
        let values = (0..rows * cols)
            .map(|index| f32::from(half::bf16::from_f32(fixtures::weight_value(name, index))))
            .collect::<Vec<_>>();
        Tensor::from_vec(values, (rows, cols), &Device::Cpu).unwrap()
    }

    #[test]
    fn the_runtime_loads_every_delta_from_the_authenticated_descriptor() {
        let (_directory, path, pinned) = fixtures::pinned();
        let runtime = H3TurboLoraRuntime::open_against(
            &path,
            &pinned,
            H3TurboLoraTier::Fl2v8StepV10,
            &Device::Cpu,
            DType::F32,
            &H3ComfyNeverCancel,
        )
        .unwrap();

        assert_eq!(runtime.tier(), H3TurboLoraTier::Fl2v8StepV10);
        assert_eq!(runtime.block_count(), 2);
        assert_eq!(runtime.token_refiner_block_count(), 1);
        assert_eq!(runtime.scale(), 0.0625);
        assert_eq!(runtime.adapter_identity_sha256().len(), 64);
        assert_eq!(
            runtime.content_sha256(),
            pinned.content_sha256.as_deref().unwrap()
        );
        assert!(runtime.main_block(2).is_none());
        assert!(runtime.token_refiner_block(1).is_none());

        // Every module's geometry, including the fused Q/K/V triple rank.
        let block = runtime.main_block(0).unwrap();
        assert_eq!(block.qkv.rank(), 12);
        assert_eq!(block.qkv.in_features(), 256);
        assert_eq!(block.qkv.out_features(), 768);
        assert_eq!(block.out.rank(), 4);
        assert_eq!(block.fc1.out_features(), 512);
        assert_eq!(block.fc2.in_features(), 256);
        for kind in H3TurboLoraModuleKind::ALL {
            // alpha/rank is uniform: the fused module's tripled alpha cancels
            // against its tripled rank.
            assert_eq!(block.kind(kind).scale(), f64::from(runtime.scale()));
        }

        // Resident bytes are the sum of every matrix, and the block figure is
        // uniform across blocks.
        let per_block = block.device_bytes();
        assert_eq!(
            runtime.device_bytes(),
            per_block * 2 + runtime.token_refiner_block(0).unwrap().device_bytes()
        );
        assert_eq!(per_block, runtime.main_block(1).unwrap().device_bytes());

        // The loaded delta reproduces the reference built from the same
        // deterministic generator, proving the offsets and BF16 decode.
        let name = "diffusion_model.blocks.0.mlp.fc2";
        let down = expected_matrix(&format!("{name}.lora_A.weight"), 4, 256);
        let up = expected_matrix(&format!("{name}.lora_B.weight"), 256, 4);
        let reference = H3TurboLoraDelta::new(&down, &up, 0.0625).unwrap();
        let x = ramp(3, 256, 77, &Device::Cpu);
        let observed = block.fc2.delta(&x).unwrap().to_vec2::<f32>().unwrap();
        let expected = reference.delta(&x).unwrap().to_vec2::<f32>().unwrap();
        for (row, expected_row) in observed.iter().zip(expected.iter()) {
            for (value, want) in row.iter().zip(expected_row.iter()) {
                assert!((value - want).abs() < 1e-5, "{value} vs {want}");
            }
        }
    }

    /// A resized adapter loads through the SAME path as a rank-uniform one:
    /// no runtime branch, no per-shape loader, no second scale authority.
    ///
    /// Its scale is exactly `1.0` — the source `alpha / rank` is already
    /// inside `lora_B`, so `affine(1.0, 0.0)` is the identity and applying the
    /// pinned `baked_scale` here would apply it twice. `H3TurboLoraDelta::new`
    /// still refuses a non-positive scale, so "baked" can never become "zero".
    #[test]
    fn a_dynamic_adapter_loads_with_unit_scale_and_per_module_ranks() {
        let tier = H3TurboLoraTier::Fl2v8StepV10Rank21;
        let (_directory, path, pinned) = fixtures::pinned_dynamic();
        let ranks = fixtures::dynamic_module_ranks(&pinned);
        let payload_bytes = std::fs::metadata(&path).unwrap().len()
            - 8
            - u64::from_le_bytes(std::fs::read(&path).unwrap()[..8].try_into().unwrap());

        // At the file's own BF16 width the resident cost IS the payload: a
        // resized adapter has no alpha scalars to subtract.
        let resident = H3TurboLoraRuntime::open_against(
            &path,
            &pinned,
            tier,
            &Device::Cpu,
            DType::BF16,
            &H3ComfyNeverCancel,
        )
        .unwrap();
        assert_eq!(resident.device_bytes(), payload_bytes);
        assert_eq!(resident.scale(), 1.0);

        let runtime = H3TurboLoraRuntime::open_against(
            &path,
            &pinned,
            tier,
            &Device::Cpu,
            DType::F32,
            &H3ComfyNeverCancel,
        )
        .unwrap();
        assert_eq!(runtime.tier(), tier);
        assert_eq!(runtime.scale(), 1.0);
        assert_eq!(runtime.block_count(), 2);
        assert_eq!(runtime.token_refiner_block_count(), 1);

        // Every block delta carries the rank the header declared for it, and
        // the ranks are genuinely different from one another.
        let mut observed = std::collections::BTreeSet::new();
        for (prefix, deltas) in [
            ("blocks.0", runtime.main_block(0).unwrap()),
            ("blocks.1", runtime.main_block(1).unwrap()),
            (
                "token_refiner.blocks.0",
                runtime.token_refiner_block(0).unwrap(),
            ),
        ] {
            for kind in H3TurboLoraModuleKind::ALL {
                let key = format!("diffusion_model.{prefix}.{}", kind.suffix());
                let delta = deltas.kind(kind);
                assert_eq!(delta.rank(), ranks[&key], "{key}");
                assert_eq!(delta.scale(), 1.0, "{key}");
                observed.insert(delta.rank());
            }
        }
        assert!(observed.len() > 2, "{observed:?} is not a varied rank set");

        // The delta is exactly `x @ (B @ A)ᵀ` — no baked scale re-applied.
        let name = "diffusion_model.blocks.0.mlp.fc2";
        let rank = ranks[name];
        let down = expected_matrix(&format!("{name}.lora_A.weight"), rank, 256);
        let up = expected_matrix(&format!("{name}.lora_B.weight"), 256, rank);
        let x = ramp(3, 256, 77, &Device::Cpu);
        let merged = up.matmul(&down).unwrap();
        let expected = x
            .matmul(&merged.t().unwrap().contiguous().unwrap())
            .unwrap()
            .to_vec2::<f32>()
            .unwrap();
        let observed = runtime
            .main_block(0)
            .unwrap()
            .fc2
            .delta(&x)
            .unwrap()
            .to_vec2::<f32>()
            .unwrap();
        for (row, expected_row) in observed.iter().zip(expected.iter()) {
            for (value, want) in row.iter().zip(expected_row.iter()) {
                assert!((value - want).abs() < 1e-4, "{value} vs {want}");
            }
        }
    }

    /// The three byte figures a resized tier charges are DERIVED from its own
    /// checked-in golden header, so a loader change that moved the charge
    /// would have to move these too.
    ///
    /// `resident` is the whole payload (no alpha scalars to subtract);
    /// `device_staging_peak` is the widest single module, because
    /// `H3TurboLoraDelta::new` builds both transposes while the originals are
    /// still live; `host_staging_peak` is twice the widest single matrix.
    #[test]
    fn dynamic_tier_bytes_derive_from_the_golden_headers() {
        for (tier, resident, widest_module, host_staging) in [
            (
                H3TurboLoraTier::Fl2v768p4StepV10Rank21,
                298_124_288u64,
                5_053_440u64,
                8_085_504u64,
            ),
            (
                H3TurboLoraTier::Fl2v8StepV10Rank21,
                326_982_656,
                8_440_320,
                13_504_512,
            ),
            (
                H3TurboLoraTier::Ref2v4StepV10Rank21,
                326_882_304,
                9_461_760,
                15_138_816,
            ),
        ] {
            let modules = super::super::turbo_lora::published_dynamic_header_modules(tier);
            assert_eq!(
                modules.len(),
                super::super::turbo_lora::H3_TURBO_LORA_MODULE_COUNT,
                "{tier:?}"
            );
            let derived_resident = modules.values().map(module_delta_bytes).sum::<u64>();
            assert_eq!(derived_resident, resident, "{tier:?}");
            // Resident == payload exactly, because there are no alphas.
            assert_eq!(
                derived_resident,
                tier.file_bytes() - 8 - tier.header_len(),
                "{tier:?}"
            );
            assert_eq!(
                modules.values().map(module_delta_bytes).max().unwrap(),
                widest_module,
                "{tier:?}"
            );
            assert_eq!(
                modules
                    .values()
                    .flat_map(|module| [&module.lora_a, &module.lora_b])
                    .map(tensor_ref_bytes)
                    .max()
                    .unwrap()
                    * 2,
                host_staging,
                "{tier:?}"
            );

            // The reason the tier exists: about 1.6 GB less resident than the
            // rank-uniform adapter it was resized from.
            let source = tier.source_tier().unwrap();
            let source_resident = super::super::turbo_lora::H3_TURBO_LORA_PAYLOAD_BYTES
                - (super::super::turbo_lora::H3_TURBO_LORA_MODULE_COUNT as u64) * 4;
            assert_eq!(source_resident, 1_956_118_528, "{source:?}");
            assert!(
                source_resident - derived_resident > 1_600_000_000,
                "{tier:?} saves only {} bytes",
                source_resident - derived_resident
            );
        }
    }

    #[cfg(target_os = "macos")]
    #[test]
    fn metal_streams_one_authenticated_main_block_and_keeps_refiners_resident() {
        let (_directory, path, pinned) = fixtures::pinned();
        let device = Device::new_metal(0).unwrap();
        let runtime = H3TurboLoraRuntime::open_metal_streamed_against(
            &path,
            &pinned,
            H3TurboLoraTier::Fl2v8StepV10,
            &device,
            DType::F32,
            Arc::new(H3ComfyNeverCancel),
        )
        .unwrap();

        assert!(runtime.is_metal_streamed());
        assert_eq!(runtime.block_count(), 2);
        assert_eq!(runtime.token_refiner_block_count(), 1);
        assert!(runtime.main_block(0).is_none());
        assert_eq!(
            runtime.device_bytes(),
            runtime.token_refiner_block(0).unwrap().device_bytes()
        );

        let block = runtime.load_main_block(1).unwrap();
        assert_eq!(
            block.device_bytes(),
            runtime.streamed_main_block_device_bytes()
        );
        let x = ramp(3, 256, 77, &device);
        let observed = block
            .fc2
            .delta(&x)
            .unwrap()
            .to_device(&Device::Cpu)
            .unwrap();
        let name = "diffusion_model.blocks.1.mlp.fc2";
        let down = expected_matrix(&format!("{name}.lora_A.weight"), 4, 256);
        let up = expected_matrix(&format!("{name}.lora_B.weight"), 256, 4);
        let reference = H3TurboLoraDelta::new(&down, &up, 0.0625).unwrap();
        let expected = reference
            .delta(&x.to_device(&Device::Cpu).unwrap())
            .unwrap();
        let observed = observed.to_vec2::<f32>().unwrap();
        let expected = expected.to_vec2::<f32>().unwrap();
        for (row, expected_row) in observed.iter().zip(expected.iter()) {
            for (value, want) in row.iter().zip(expected_row.iter()) {
                assert!((value - want).abs() < 1e-4, "{value} vs {want}");
            }
        }

        // Random access remains valid after a completed block so a base-block
        // construction failure can retry without desynchronizing the adapter.
        assert_eq!(
            runtime.load_main_block(0).unwrap().device_bytes(),
            runtime.streamed_main_block_device_bytes()
        );
    }

    #[test]
    fn the_runtime_refuses_to_load_without_an_authenticated_digest() {
        let (_directory, path, mut pinned) = fixtures::pinned();
        pinned.content_sha256 = None;
        let error = H3TurboLoraRuntime::open_against(
            &path,
            &pinned,
            H3TurboLoraTier::Fl2v8StepV10,
            &Device::Cpu,
            DType::F32,
            &H3ComfyNeverCancel,
        )
        .unwrap_err();
        assert_eq!(error.code, H3TurboLoraErrorCode::MissingContentPin);
    }

    #[test]
    fn the_runtime_requires_a_floating_compute_dtype() {
        let (_directory, path, pinned) = fixtures::pinned();
        let error = H3TurboLoraRuntime::open_against(
            &path,
            &pinned,
            H3TurboLoraTier::Fl2v8StepV10,
            &Device::Cpu,
            DType::U8,
            &H3ComfyNeverCancel,
        )
        .unwrap_err();
        assert_eq!(error.code, H3TurboLoraErrorCode::DTypeMismatch);
    }

    #[test]
    fn an_absent_delta_is_the_identity() {
        let device = Device::Cpu;
        let x = Tensor::new(&[[1.0f32, 2.0, 3.0]], &device).unwrap();
        let base = Tensor::new(&[[7.0f32, 8.0]], &device).unwrap();
        let passed = apply_optional_turbo_delta(None, &x, base.clone()).unwrap();
        assert_eq!(
            passed.to_vec2::<f32>().unwrap(),
            base.to_vec2::<f32>().unwrap()
        );
    }
}
